import{it,expect,vi,beforeEach}from'vitest';
import{analyzePlan}from'./analyzePlan';
import{readPlanOcr}from'./readPlanOcr';
import{detectPlanWalls}from'./detectPlanWalls';
vi.mock('./readPlanOcr',()=>({readPlanOcr:vi.fn()}));vi.mock('./detectPlanWalls',()=>({detectPlanWalls:vi.fn()}));
const page={imageUrl:'image',widthPx:100,heightPx:100,textSource:'none' as const};
beforeEach(()=>{vi.resetAllMocks();vi.mocked(readPlanOcr).mockResolvedValue([{text:'3200',source:'ocr',box:{x:0,y:0,width:40,height:10}}]);vi.mocked(detectPlanWalls).mockResolvedValue([{id:'line',start:{x:0,y:0},end:{x:90,y:0},thicknessPx:1}]);});
it('automatically combines OCR and line analysis without changing input',async()=>{const result=await analyzePlan(page,new AbortController().signal);expect(result.analysis).toMatchObject({numericCount:1,textState:'complete',lineState:'complete'});expect(result.analysis?.lines).toHaveLength(1);expect(result.labels?.[0].text).toBe('3200');expect(page).not.toHaveProperty('analysis');});
it('uses existing PDF evidence instead of running redundant OCR',async()=>{const result=await analyzePlan({...page,textSource:'pdf-text',labels:[]},new AbortController().signal);expect(readPlanOcr).not.toHaveBeenCalled();expect(result.textSource).toBe('pdf-text');expect(detectPlanWalls).toHaveBeenCalledOnce();});
it('preserves partial results and reports failed stages',async()=>{vi.mocked(readPlanOcr).mockRejectedValue(new Error('OCR failed'));const result=await analyzePlan(page,new AbortController().signal);expect(result.analysis?.textState).toBe('failed');expect(result.analysis?.lines).toHaveLength(1);expect(result.analysis?.issues.join(' ')).toContain('읽지 못');});
it('does not deliver a completed result after cancellation',async()=>{const c=new AbortController();vi.mocked(readPlanOcr).mockImplementation(async()=>{c.abort();return [];});await expect(analyzePlan(page,c.signal)).rejects.toThrow('취소');});
