import {uuidPattern} from '../domain/cloudProject';
import {parseLibraryKind,type LibraryKind} from '../domain/cloudLibrary';
export interface LibraryLink {userId:string;kind:LibraryKind;localId:string;remoteId:string;remoteRevision:number;localRevision:number;sha256:string}
function parse(v:unknown):LibraryLink{const r=v as LibraryLink;if(!r||!uuidPattern.test(r.userId)||!uuidPattern.test(r.remoteId)||!uuidPattern.test(r.localId)||!Number.isSafeInteger(r.remoteRevision)||r.remoteRevision<1||!Number.isSafeInteger(r.localRevision)||r.localRevision<1||!/^[0-9a-f]{64}$/.test(r.sha256))throw new Error('계정 라이브러리 연결이 올바르지 않습니다.');return {...r,kind:parseLibraryKind(r.kind)};}
const req=<T>(r:IDBRequest<T>)=>new Promise<T>((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
const finished=(tx:IDBTransaction)=>{const p=new Promise<void>((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onabort=()=>reject(tx.error??new Error('연결 저장 실패'));tx.onerror=()=>{};});void p.catch(()=>{});return p;};
export function createLibraryLinks(factory:IDBFactory=globalThis.indexedDB,name='gonggan-cloud-library-links-v1'){
 let connection:Promise<IDBDatabase>|undefined;const open=()=>connection??=new Promise<IDBDatabase>((resolve,reject)=>{if(!factory){reject(new Error('이 브라우저에서는 계정 연결을 저장할 수 없습니다.'));return;}const r=factory.open(name,1);r.onupgradeneeded=()=>{const store=r.result.createObjectStore('links',{keyPath:['userId','kind','localId']});store.createIndex('remote',['userId','kind','remoteId'],{unique:true});};r.onsuccess=()=>{r.result.onversionchange=()=>{r.result.close();connection=undefined;};resolve(r.result);};r.onerror=()=>{connection=undefined;reject(r.error);};r.onblocked=()=>{connection=undefined;reject(new Error('다른 탭의 라이브러리를 닫고 다시 시도해주세요.'));};});
 async function find(key:[string,LibraryKind,string],remote=false){const db=await open(),tx=db.transaction('links'),done=finished(tx),store=tx.objectStore('links'),raw=await req(remote?store.index('remote').get(key):store.get(key));await done;return raw?parse(raw):undefined;}
 return {local:(user:string,kind:LibraryKind,id:string)=>find([user,kind,id]),remote:(user:string,kind:LibraryKind,id:string)=>find([user,kind,id],true),
  async save(value:LibraryLink,expectedRemoteRevision:number,expectedMapping:{localId:string;revision:number}|null){const link=parse(value),db=await open(),tx=db.transaction('links','readwrite'),done=finished(tx),store=tx.objectStore('links');try{const old=await req(store.get([link.userId,link.kind,link.localId])) as LibraryLink|undefined;if(expectedRemoteRevision!==undefined&&(old?.remoteRevision??0)!==expectedRemoteRevision)throw new Error('다른 탭에서 계정 연결을 변경했습니다. 다시 확인해주세요.');const other=await req(store.index('remote').get([link.userId,link.kind,link.remoteId])) as LibraryLink|undefined;if((other?.localId??null)!==(expectedMapping?.localId??null)||(other?.remoteRevision??0)!==(expectedMapping?.revision??0))throw new Error('다른 탭에서 원격 항목 연결을 변경했습니다.');if(other&&other.localId!==link.localId)store.delete([other.userId,other.kind,other.localId]);store.put(link);await done;}catch(e){try{tx.abort();}catch{/* Done. */}await done.catch(()=>{});throw e;}},
 };
}
let singleton:ReturnType<typeof createLibraryLinks>|undefined;export const libraryLinks=()=>singleton??=createLibraryLinks();
