import {describe,it,expect} from 'vitest';
import JSZip from 'jszip';
import {artworkModelBytes,readModelArtworkFiles} from './modelArtworkImport';
import {artworkTestGlb,artworkTestGltf} from './modelArtworkTestFixture';
import {inspectStaticArtworkGlb,packEmbeddedGltf} from './artworkModelPayload';
const file=(name:string,bytes:ArrayBuffer|Uint8Array|string)=>new File([typeof bytes==='string'?bytes:bytes instanceof Uint8Array?bytes.slice().buffer:bytes],name);
async function zipModel(entries:Map<string,Uint8Array|string>){const zip=new JSZip();for(const [name,value] of entries)zip.file(name,value);return file('artwork.zip',await zip.generateAsync({type:'uint8array'}));}
describe('real GLB and glTF artwork inputs',()=>{
 it('embeds PNG bytes without resampling and checks excessive dimensions before decoding',()=>{
  const {doc}=artworkTestGltf(),png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a2ioAAAAASUVORK5CYII=',withImage={...doc,images:[{uri:'data:image/png;base64,'+png}]},result=inspectStaticArtworkGlb(packEmbeddedGltf(withImage));expect(result.images[0].uri).toBeUndefined();expect(result.images[0].mimeType).toBe('image/png');const bytes=Uint8Array.from(atob(png),c=>c.charCodeAt(0));new DataView(bytes.buffer).setUint32(16,9000);const invalid={...withImage,images:[{uri:'data:image/png;base64,'+btoa(String.fromCharCode(...bytes))}]};expect(()=>packEmbeddedGltf(invalid)).toThrow('8192px');
 });
 it('reads an uncompressed GLB with actual bounds and keeps its original bytes',async()=>{const bytes=artworkTestGlb(),model=await readModelArtworkFiles([file('arch.glb',bytes)]);expect(model.sizeMm).toEqual([expect.closeTo(1200),expect.closeTo(2100),expect.closeTo(900)]);expect(model.sourceOffsetM).toEqual([-10,expect.closeTo(-2),-5]);expect(Uint8Array.from(atob(model.dataUrl.split(',')[1]),c=>c.charCodeAt(0))).toEqual(new Uint8Array(bytes));});
 it('merges multiple embedded glTF buffers into one GLB without changing accessor offsets',async()=>{const {doc}=artworkTestGltf(),result=await artworkModelBytes([file('arch.gltf',JSON.stringify(doc))]),packed=inspectStaticArtworkGlb(result.bytes);expect(packed.buffers).toHaveLength(1);expect(packed.bufferViews[2].buffer).toBe(0);expect(packed.bufferViews[2].byteOffset).toBe(doc.buffers[0].byteLength);expect((await readModelArtworkFiles([file('arch.gltf',JSON.stringify(doc))])).sizeMm[1]).toBeCloseTo(2100);});
 it('reads nested ZIP resources, including relative parent paths, with no remote requests',async()=>{const {doc,files}=artworkTestGltf(true);doc.buffers.forEach(b=>b.uri='../'+b.uri);const zip=await zipModel(new Map<string,Uint8Array|string>([...files,['models/arch.gltf',JSON.stringify(doc)]]));const model=await readModelArtworkFiles([zip]);expect(model.name).toBe('arch.gltf');expect(model.sizeMm[0]).toBeCloseTo(1200);expect(inspectStaticArtworkGlb((await artworkModelBytes([zip])).bytes).buffers[0].uri).toBeUndefined();});
 it('accepts companion files selected together and fails clearly when a resource is missing',async()=>{const {doc,files}=artworkTestGltf(true);doc.buffers.forEach(b=>b.uri=b.uri.split('/').pop()!);const companions=[file('arch.gltf',JSON.stringify(doc)),...Array.from(files,([name,b])=>file(name.split('/').pop()!,b))];expect((await readModelArtworkFiles(companions)).sizeMm[2]).toBeCloseTo(900);await expect(artworkModelBytes(companions.slice(0,2))).rejects.toThrow('누락');});
 it('rejects remote, escaping, duplicate, ambiguous and over-budget input before loading',async()=>{const source=artworkTestGltf(true);source.doc.buffers[0].uri='https://example.com/private.bin';await expect(artworkModelBytes([file('arch.gltf',JSON.stringify(source.doc))])).rejects.toThrow('상대 경로');source.doc.buffers[0].uri='../../shape.bin';await expect(artworkModelBytes([file('arch.gltf',JSON.stringify(source.doc))])).rejects.toThrow('밖');await expect(artworkModelBytes([file('same.bin','a'),file('same.bin','b')])).rejects.toThrow('중복');await expect(artworkModelBytes([file('a.gltf','{}'),file('b.gltf','{}')])).rejects.toThrow('하나');await expect(artworkModelBytes([file('big.glb',new Uint8Array(12*1024*1024+1))])).rejects.toThrow('12MB');});
 it('rejects animated, compressed, cyclic, morphing and invalid buffer models',()=>{const {doc}=artworkTestGltf();expect(()=>packEmbeddedGltf({...doc,animations:[{}]})).toThrow('움직이는');expect(()=>packEmbeddedGltf({...doc,extensionsRequired:['KHR_draco_mesh_compression']})).toThrow('압축');expect(()=>packEmbeddedGltf({...doc,nodes:[{children:[0]}]})).toThrow('연결');expect(()=>packEmbeddedGltf({...doc,meshes:[{primitives:[{...doc.meshes[0].primitives[0],targets:[]}]}]})).toThrow('변형');expect(()=>packEmbeddedGltf({...doc,buffers:[{...doc.buffers[0],byteLength:1},doc.buffers[1]]})).toThrow('범위');const b=artworkTestGlb(),v=new DataView(b);v.setUint32(20+v.getUint32(12,true),100000,true);expect(()=>inspectStaticArtworkGlb(b)).toThrow('범위');});
 it('bounds non-position accessors and repeated mesh instances before loader allocation',()=>{const {doc}=artworkTestGltf();const oversized=structuredClone(doc);oversized.accessors[1].count=600001;expect(()=>packEmbeddedGltf(oversized)).toThrow('정점 자산');const repeated=structuredClone(doc);repeated.accessors[2].count=300001;repeated.meshes=repeated.meshes.slice(0,1);repeated.nodes.forEach(n=>n.mesh=0);expect(()=>packEmbeddedGltf(repeated)).toThrow('20만');const shared=structuredClone(doc);shared.nodes[0]=Object.assign(shared.nodes[0],{children:[2,2]});expect(()=>packEmbeddedGltf(shared)).toThrow('중복 연결');});
 it('rejects ZIP traversal and a false declared expansion size before decompression',async()=>{await expect(artworkModelBytes([await zipModel(new Map([['../a.gltf','{}']]))])).rejects.toThrow('경로');const zip=await zipModel(new Map([['a.gltf',JSON.stringify(artworkTestGltf().doc)]])),raw=new Uint8Array(await zip.arrayBuffer()),view=new DataView(raw.buffer);for(let i=0;i<raw.length-46;i++)if(view.getUint32(i,true)===0x02014b50){view.setUint32(i+24,12*1024*1024+1,true);break;}await expect(artworkModelBytes([file('large.zip',raw)])).rejects.toThrow('푼 크기');});
});
