import {expect,it} from 'vitest';
import {createDemoProject,parseProject,deleteSelection,duplicateSelection} from './model';
import {addModelArtwork,modelArtworkCorners,transformModelArtworks,patchModelArtwork} from './modelArtworks';
import {addMeasurement,fixedAnchor,modelArtworkAnchor,resolveAnchor,resolveMeasurement} from './measurements';
import {testArtworkModel} from '../lib/modelArtworkTestFixture';
import {createPublicShare} from './publicShare';
const fixture=()=>addModelArtwork(createDemoProject(),testArtworkModel());
it('keeps exact model corner coordinates attached through XYZ rotation, translation and size edits',()=>{const {project,artwork:a}=fixture(),point=modelArtworkCorners(a)[7],anchor=modelArtworkAnchor(project,a.id,point),dimension=addMeasurement(project,'3d',anchor,fixedAnchor({x:1000,y:0,z:0})).dimensions![0],moved=transformModelArtworks(project,[a.id],a.id,{x:500,y:300,z:-800},{x:20,y:45,z:30}),corner=modelArtworkCorners(moved.modelArtworks![0])[7];const result=resolveMeasurement(moved,dimension);expect(result.start.x).toBeCloseTo(corner.x);expect(result.start.y).toBeCloseTo(corner.y);expect(result.start.z).toBeCloseTo(corner.z);const resized=patchModelArtwork(moved,a.id,{widthMm:2400,heightMm:4200,depthMm:1800}),updated=modelArtworkCorners(resized.modelArtworks![0])[7];expect(resolveAnchor(resized,anchor).point.x).toBeCloseTo(updated.x);expect(resolveAnchor(resized,anchor).point.y).toBeCloseTo(updated.y);expect(resolveAnchor(resized,anchor).point.z).toBeCloseTo(updated.z);});
it('preserves last position on deletion, retains detached semantics and never reattaches a new model to the old ID',()=>{const {project,artwork:a}=fixture(),anchor=modelArtworkAnchor(project,a.id,modelArtworkCorners(a)[7]),measured=addMeasurement(project,'3d',anchor,fixedAnchor({x:5000,y:0,z:0})),moved=transformModelArtworks(measured,[a.id],a.id,{x:700,y:0,z:300},{x:0,y:45,z:0}),last=resolveMeasurement(moved,moved.dimensions![0]).start,deleted=deleteSelection(moved,{type:'modelArtwork',id:a.id});expect(resolveMeasurement(deleted,deleted.dimensions![0]).start).toEqual(last);expect(resolveMeasurement(deleted,deleted.dimensions![0]).detached).toBe(true);const next=addModelArtwork(deleted,testArtworkModel());expect(next.artwork.id).not.toBe(a.id);expect(resolveMeasurement(next.project,next.project.dimensions![0]).detached).toBe(true);});
it('round-trips anchors and rejects malformed coordinates without affecting old fixed and wall anchors',()=>{const {project,artwork:a}=fixture(),anchor=modelArtworkAnchor(project,a.id,modelArtworkCorners(a)[7]),p=addMeasurement(project,'3d',anchor,fixedAnchor({x:0,y:0,z:0}));expect(parseProject(p).dimensions).toEqual(p.dimensions);expect(()=>modelArtworkAnchor(p,a.id,{x:1e9,y:0,z:0})).toThrow('좌표');const invalid=structuredClone(p);(invalid.dimensions![0].start as typeof anchor&{localRatio:{x:number;y:number;z:number}}).localRatio.x=NaN;expect(()=>parseProject(invalid)).toThrow('좌표');});
it('publishes resolved coordinates only for visible referenced models',()=>{const {project,artwork:a}=fixture(),anchor=modelArtworkAnchor(project,a.id,modelArtworkCorners(a)[7]),p=addMeasurement(project,'3d',anchor,fixedAnchor({x:1000,y:0,z:0})),options={includeDimensions:true,modelAssetIds:new Map([[a.id,'a'.repeat(64)]])},snapshot=createPublicShare(p,options).snapshot;expect(snapshot.dimensions![0].start).toEqual(resolveAnchor(p,anchor).point);expect(JSON.stringify(snapshot.dimensions)).not.toContain('localRatio');expect(createPublicShare(patchModelArtwork(p,a.id,{visible:false}),options).snapshot.dimensions).toEqual([]);});
it('reserves IDs still present in saved Scene dimensions',()=>{const {project,artwork:a}=fixture(),anchor=modelArtworkAnchor(project,a.id,modelArtworkCorners(a)[7]),p=addMeasurement(project,'3d',anchor,fixedAnchor({x:5000,y:0,z:0}));p.scenes=[{id:'saved',name:'measured',artworks:[],wallVisibility:{},structure:{walls:p.walls,modelArtworks:p.modelArtworks,openings:[],dimensions:p.dimensions!,unplacedArtworks:[]}}];const empty={...p,modelArtworks:[],dimensions:[]};expect(addModelArtwork(empty,testArtworkModel()).artwork.id).not.toBe(a.id);});

it('does not reuse detached measurement IDs when duplicating a different model',()=>{const {project,artwork:a}=fixture(),anchor=modelArtworkAnchor(project,a.id,modelArtworkCorners(a)[7]),measured=addMeasurement(project,'3d',anchor,fixedAnchor({x:5000,y:0,z:0})),deleted=deleteSelection(measured,{type:'modelArtwork',id:a.id}),added=addModelArtwork(deleted,testArtworkModel()),copy=duplicateSelection(added.project,{type:'modelArtwork',id:added.artwork.id});expect(copy.selection.id).not.toBe(a.id);expect(resolveMeasurement(copy.project,copy.project.dimensions![0]).detached).toBe(true);});
