import {describe,expect,it} from 'vitest';
import {createDemoProject} from './model';
import {addModelArtwork,modelArtworkBounds,modelArtworkCorners} from './modelArtworks';
import {snapModelArtworkTransform} from './modelArtworkSnap';
import {testArtworkModel} from '../lib/modelArtworkTestFixture';
import type {Project,WorldPoint} from './types';
const zero={x:0,y:0,z:0},options={toleranceMm:{x:100,y:100,z:100}};
function fixture(){const {project,artwork}=addModelArtwork(createDemoProject(),testArtworkModel());return {...project,walls:[],artworks:[],modelArtworks:[{...artwork,id:'moving',widthMm:400,heightMm:500,depthMm:200,position:{x:1000,y:0,z:1000}},{...artwork,id:'target',widthMm:400,heightMm:500,depthMm:200,position:{x:2000,y:0,z:1000}}]} as Project;}
const snap=(p:Project,pos:WorldPoint,rotation=zero,extra={})=>snapModelArtworkTransform(p,['moving'],'moving',pos,rotation,{...options,...extra});
describe('3D artwork inference',()=>{
 it('aligns edges and centres without changing assets, dimensions or stationary items',()=>{const p=fixture(),r=snap(p,{x:1560,y:0,z:1020});expect(r.project.modelArtworks![0].position).toEqual({x:1600,y:0,z:1000});expect(r.guides.some(g=>g.kind==='edge'&&g.targetId==='target')).toBe(true);expect(r.project.modelArtworks![1]).toEqual(p.modelArtworks![1]);expect(r.project.modelArtworks![0].model).toEqual(p.modelArtworks![0].model);expect(r.project.modelArtworks![0].widthMm).toBe(400);expect(snap(p,{x:1980,y:0,z:1000}).project.modelArtworks![0].position.x).toBe(2000);});
 it('uses rotated outer bounds for edge contacts',()=>{const p=fixture(),r=snap(p,{x:1680,y:0,z:1000},{x:0,y:90,z:0});expect(modelArtworkBounds(r.project.modelArtworks![0]).maxX).toBeCloseTo(modelArtworkBounds(p.modelArtworks![1]).minX);expect(r.project.modelArtworks![0].rotation.y).toBeCloseTo(90);});
 it('keeps rigid group spacing and places its lowest tipped member on the floor',()=>{const p=fixture();p.modelArtworks=p.modelArtworks!.map((a,i)=>({...a,groupId:'group',position:{x:1000+i*600,y:250,z:1000},rotation:{x:0,y:0,z:45}}));const low=Math.min(...p.modelArtworks!.map(a=>modelArtworkBounds(a).minY)),a=p.modelArtworks![0];const r=snapModelArtworkTransform(p,['moving','target'],'moving',{...a.position,y:a.position.y-low+30},a.rotation,{...options,axes:['y']});expect(Math.min(...r.project.modelArtworks!.map(a=>modelArtworkBounds(a).minY))).toBeCloseTo(0);expect(r.project.modelArtworks![1].position.x-r.project.modelArtworks![0].position.x).toBeCloseTo(600);expect(r.guides).toHaveLength(1);expect(r.guides[0].kind).toBe('floor');});
 it('limits a rotated gizmo to its actual world direction',()=>{const p=fixture(),dir={x:1,y:0,z:1},r=snap(p,{x:1580,y:0,z:1580},zero,{direction:dir,directionToleranceMm:100});const a=r.project.modelArtworks![0];expect(a.position.x).toBeCloseTo(1600);expect(a.position.z).toBeCloseTo(1600);expect(a.position.x-a.position.z).toBeCloseTo(0);expect(r.guides[0].normal.x*r.guides[0].point.x+r.guides[0].normal.z*r.guides[0].point.z).toBeCloseTo(r.guides[0].constantMm);});
 it('snaps to arbitrary finite wall faces using eight corners and ignores wall extensions',()=>{const p=fixture();p.modelArtworks=p.modelArtworks!.slice(0,1);p.walls=[{...createDemoProject().walls[0],start:{x:0,z:0},end:{x:4000,z:4000},thicknessMm:200}];const a=p.modelArtworks[0],pos={x:1600,y:0,z:1600+300+100*Math.SQRT2+20},r=snap(p,pos,zero,{axes:['x','z']});const contacts=modelArtworkCorners(r.project.modelArtworks![0]).map(c=>(c.z-c.x)/Math.SQRT2);expect(Math.min(...contacts)).toBeCloseTo(100);expect(r.guides.some(g=>g.kind==='wall')).toBe(true);const outside=snap(p,{x:8000,y:0,z:8440},a.rotation,{axes:['x','z']});expect(outside.guides).toEqual([]);});
 it('bypasses all snapping, grids only movable axes, ignores hidden targets and rejects locks',()=>{const p=fixture(),pos={x:1567.25,y:18.5,z:1234.5};expect(snap(p,pos,zero,{bypass:true}).project.modelArtworks![0].position).toEqual(pos);p.modelArtworks![1].visible=false;const r=snap(p,pos,zero,{axes:['x','z']});expect(r.project.modelArtworks![0].position).toEqual({x:1570,y:18.5,z:1230});expect(r.guides).toEqual([]);p.modelArtworks![0].locked=true;expect(()=>snap(p,pos)).toThrow('잠긴');});
 it('rejects invalid tolerances and directions and keeps the source immutable',()=>{const p=fixture(),before=structuredClone(p);expect(()=>snap(p,zero,zero,{toleranceMm:{x:NaN,y:100,z:100}})).toThrow('범위');expect(()=>snap(p,zero,zero,{direction:zero,directionToleranceMm:100})).toThrow('방향');expect(()=>snap(p,zero,zero,{direction:{x:1,y:0,z:0},directionToleranceMm:-1})).toThrow('방향');snap(p,{x:1560,y:0,z:1000});expect(p).toEqual(before);});
});
