/** Synthetic identities and real SQLite transactions. Never imported in production. */
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {handleProjectRequest,type ProjectDatabase,type ProjectStatement,type ProjectBucket} from './projectApi';
import type {AuthFetch} from './auth';
import {cloudPackageHash} from '../lib/cloudProjectClient';
import {encodeCloudMetadata} from '../domain/cloudProject';
export const collaborationUsers={a:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',b:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',c:'cccccccc-cccc-4ccc-8ccc-cccccccccccc',d:'dddddddd-dddd-4ddd-8ddd-dddddddddddd'};
export function collaborationFixture(){
 const sql=new DatabaseSync(':memory:');for(const file of ['0001_cloud_projects.sql','0004_review_comments.sql','0005_project_collaboration.sql'])sql.exec(readFileSync(new URL('../../migrations/'+file,import.meta.url),'utf8'));
 const operations=new WeakMap<ProjectStatement,()=>{success:boolean;meta:{changes:number}}>();const state={lostBatch:false,beforePut:undefined as (()=>Promise<void>)|undefined,beforeRun:undefined as ((query:string)=>void)|undefined};
 const db:ProjectDatabase={prepare(query){let values:unknown[]=[];const execute=()=>{state.beforeRun?.(query);const r=sql.prepare(query).run(...values as Parameters<ReturnType<DatabaseSync['prepare']>['run']>);return {success:true,meta:{changes:Number(r.changes)}};};const statement:ProjectStatement={bind(...args){values=args;return this;},async first<T>(){return (sql.prepare(query).get(...values as Parameters<ReturnType<DatabaseSync['prepare']>['get']>)??null) as T|null;},async all<T>(){return {results:sql.prepare(query).all(...values as Parameters<ReturnType<DatabaseSync['prepare']>['all']>) as T[]};},async run(){return execute();}};operations.set(statement,execute);return statement;},async batch(statements){sql.exec('BEGIN IMMEDIATE');let results;try{results=statements.map(s=>operations.get(s)!());sql.exec('COMMIT');}catch(e){sql.exec('ROLLBACK');throw e;}if(state.lostBatch){state.lostBatch=false;throw new Error('synthetic lost committed batch response');}return results;}};
 const files=new Map<string,Uint8Array<ArrayBuffer>>(),bucket:ProjectBucket={async put(key,stream,options){const bytes=new Uint8Array(await new Response(stream).arrayBuffer());if(await cloudPackageHash(bytes.buffer)!==options.sha256)throw new Error('hash mismatch');await state.beforePut?.();files.set(key,bytes);return {size:bytes.length};},async get(key,options){const bytes=files.get(key);if(!bytes)return null;const subset=options?bytes.slice(options.range.offset,options.range.offset+options.range.length):bytes;return {body:new Response(subset).body!,size:bytes.length};},async delete(key){files.delete(key);}};
 const auth:AuthFetch=async(_input,init)=>{const token=new Headers(init?.headers).get('authorization')?.replace('Bearer ','')??'',name=token.replace('-unverified','') as keyof typeof collaborationUsers,id=collaborationUsers[name];return id?Response.json({id,email:name+'@example.test',email_confirmed_at:token.endsWith('-unverified')?null:'2026-10-07T00:00:00Z',role:'authenticated',aud:'authenticated',is_anonymous:false,created_at:'2026-10-07T00:00:00Z'}):Response.json({message:'invalid JWT'},{status:401});};
 const env={PROJECTS_DB:db,PRIVATE_PROJECTS:bucket,SUPABASE_URL:'https://testing.supabase.co',SUPABASE_PUBLISHABLE_KEY:'sb_publishable_only_public_test_key'};
 const bridge=async(path:string,init:RequestInit={})=>{const headers=new Headers(init.headers);if(init.body instanceof Blob)headers.set('content-length',String(init.body.size));else if(typeof init.body==='string')headers.set('content-length',String(new TextEncoder().encode(init.body).length));return handleProjectRequest(new Request('https://example.test'+path,{...init,headers}),env,auth);};
 const call=(method:string,path:string,token='a',value?:unknown)=>bridge(path,{method,headers:{authorization:'Bearer '+token,'content-type':'application/json'},...(value===undefined?{}:{body:JSON.stringify(value)})});
 const id=crypto.randomUUID(),zip=new Blob([new Uint8Array([80,75,3,4,...Array(26).fill(0)])]),meta={name:'비공개 전시',venue:'공간',sourceProjectId:'private-local'};
 async function save(token='a',expected=0,file=zip){return bridge('/api/projects/'+id,{method:'PUT',headers:{authorization:'Bearer '+token,'content-type':'application/zip','x-project-sha256':await cloudPackageHash(await file.arrayBuffer()),'x-project-metadata':encodeCloudMetadata(meta),'x-expected-revision':String(expected)},body:file});}
 async function invite(role='editor',token='b'){const value={id:crypto.randomUUID(),email:token+'@example.test',role,token:'1'.repeat(24)+crypto.randomUUID().replace(/-/g,'').slice(0,24)};const r=await call('POST',`/api/projects/${id}/invitations`,'a',value);if(r.status!==201)throw new Error(await r.text());return value;}
 const accept=(value:{id:string;token:string},token='b',action='accept')=>call('POST',`/api/project-invitations/${value.id}/${action}`,token,{token:value.token});
 const member=(role:string,revoked=false,expectedRevision=1,token='b')=>call('PATCH',`/api/projects/${id}/members/${collaborationUsers[token as keyof typeof collaborationUsers]}`,'a',{role,revoked,expectedRevision});
 return {sql,db,env,state,files,bridge,call,id,zip,meta,save,invite,accept,member,close:()=>sql.close()};
}
