import type {ProjectDatabase} from './projectApi';
import {projectAccess} from './projectAccess';
import {CollaborationInputError,inviteId,inviteToken,inviteTokenHash,inviteEmail,memberRole,PROJECT_MEMBER_MAX,PROJECT_INVITE_MAX,SHARED_PROJECT_MAX,INVITE_DURATION_MS,type ProjectInvitation,type ProjectMember} from '../domain/collaboration';
import {uuidPattern} from '../domain/cloudProject';
interface InviteRow {id:string;project_id:string;recipient_email:string;role:string;token_hash:string;revision:number;status:'pending'|'accepted'|'revoked';accepted_by:string|null;expires_at:string;created_at:string;updated_at:string}
interface MemberRow {user_id:string;recipient_email:string;role:string;revision:number;revoked:number;created_at:string;updated_at:string}
const headers={'cache-control':'no-store','x-content-type-options':'nosniff'},json=(v:unknown,status=200)=>Response.json(v,{status,headers}),fail=(status:number,error:string)=>json({error},status);
const invitation=(r:InviteRow):ProjectInvitation=>({id:r.id,projectId:r.project_id,email:r.recipient_email,role:memberRole(r.role),revision:r.revision,status:r.status,expiresAt:r.expires_at,createdAt:r.created_at});
const member=(r:MemberRow):ProjectMember=>({userId:r.user_id,email:r.recipient_email,role:memberRole(r.role),revision:r.revision,revoked:r.revoked===1,createdAt:r.created_at,updatedAt:r.updated_at});
async function body(request:Request){const reader=request.body?.getReader();if(!reader)throw new CollaborationInputError('초대 요청이 필요합니다.');const chunks:Uint8Array[]=[];let length=0;try{while(true){const p=await reader.read();if(p.done)break;length+=p.value.length;if(length>4096){await reader.cancel();throw new CollaborationInputError('초대 요청은 4KiB 이하여야 합니다.');}chunks.push(p.value);}}finally{reader.releaseLock();}const bytes=new Uint8Array(length);let offset=0;for(const p of chunks){bytes.set(p,offset);offset+=p.length;}const v=JSON.parse(new TextDecoder('utf8',{fatal:true}).decode(bytes));if(!v||typeof v!=='object'||Array.isArray(v))throw new CollaborationInputError('초대 요청이 올바르지 않습니다.');return v as Record<string,unknown>;}
const revision=(v:unknown)=>{if(!Number.isSafeInteger(v)||(v as number)<1)throw new CollaborationInputError('참여자/초대 버전이 필요합니다.');return v as number;};
/** Owner-only member administration. Does not send mail or expose invite secrets in lists. */
export async function handleCollaborationRequest(request:Request,db:ProjectDatabase,user:{id:string;email:string}):Promise<Response>{
 const url=new URL(request.url),method=request.method,accept=/^\/api\/project-invitations\/([0-9a-f-]{36})\/(preview|accept)$/.exec(url.pathname);
 try{
  if(accept){
   if(method!=='POST')return fail(405,'지원하지 않는 초대 요청입니다.');inviteId(accept[1]);const value=await body(request),token=inviteToken(value.token),hash=await inviteTokenHash(token),email=inviteEmail(user.email),now=new Date().toISOString();
   const invite=await db.prepare('SELECT * FROM project_invites WHERE id = ? AND token_hash = ? AND recipient_email = ?').bind(accept[1],hash,email).first<InviteRow>();if(!invite)return fail(404,'이 계정의 초대를 찾을 수 없습니다.');
   const parent=await db.prepare('SELECT id, owner_id, name, venue, archived FROM cloud_projects WHERE id = ?').bind(invite.project_id).first<{id:string;owner_id:string;name:string;venue:string;archived:number}>();if(!parent||parent.archived)return fail(409,'초대한 프로젝트가 보관됐거나 없습니다.');if(parent.owner_id===user.id)return fail(409,'소유자는 자기 프로젝트 초대를 수락할 수 없습니다.');
   if(invite.status==='revoked')return fail(410,'취소된 초대입니다.');
   if(invite.status==='accepted'){const access=await projectAccess(db,parent.id,user.id);if(invite.accepted_by!==user.id||!access)return fail(410,'더 이상 유효하지 않은 초대입니다.');return json({projectId:parent.id,name:parent.name,venue:parent.venue,role:access.role,accepted:true});}
   if(invite.expires_at<=now)return fail(410,'만료된 초대입니다.');
   if(accept[2]==='preview')return json({projectId:parent.id,name:parent.name,venue:parent.venue,role:memberRole(invite.role),expiresAt:invite.expires_at,accepted:false});
   if(!db.batch)return fail(503,'초대의 원자적 저장 연결이 아직 준비되지 않았습니다.');
   // Both statements execute in a single D1 transaction. Retry never re-grants a revoked membership.
   const grant=db.prepare('INSERT INTO project_members (project_id, user_id, recipient_email, role, revision, revoked, grant_invite_id, created_at, updated_at) SELECT project_id, ?, recipient_email, role, 1, 0, id, ?, ? FROM project_invites i WHERE i.id = ? AND i.token_hash = ? AND i.recipient_email = ? AND i.status = \'pending\' AND i.expires_at > ? AND EXISTS (SELECT 1 FROM cloud_projects p WHERE p.id = i.project_id AND p.archived = 0 AND p.owner_id != ?) AND NOT EXISTS (SELECT 1 FROM project_members m WHERE m.project_id = i.project_id AND m.user_id = ? AND m.revoked = 0) AND (SELECT COUNT(*) FROM project_members m WHERE m.project_id = i.project_id AND m.revoked = 0) < ? AND (SELECT COUNT(*) FROM project_members m WHERE m.user_id = ? AND m.revoked = 0) < ? ON CONFLICT(project_id,user_id) DO UPDATE SET recipient_email = excluded.recipient_email, role = excluded.role, revision = project_members.revision + 1, revoked = 0, grant_invite_id = excluded.grant_invite_id, updated_at = excluded.updated_at WHERE project_members.revoked = 1').bind(user.id,now,now,invite.id,hash,email,now,user.id,user.id,PROJECT_MEMBER_MAX,user.id,SHARED_PROJECT_MAX);
   const used=db.prepare('UPDATE project_invites SET status = \'accepted\', accepted_by = ?, revision = revision + 1, updated_at = ? WHERE id = ? AND status = \'pending\' AND token_hash = ? AND recipient_email = ? AND expires_at > ? AND EXISTS (SELECT 1 FROM project_members m WHERE m.project_id = project_invites.project_id AND m.user_id = ? AND m.grant_invite_id = project_invites.id AND m.revoked = 0)').bind(user.id,now,invite.id,hash,email,now,user.id);
   const results=await db.batch([grant,used]);if(results.some(r=>!r.success))throw new Error('초대 저장 결과를 확인하지 못했습니다.');
   const current=await db.prepare('SELECT status, accepted_by FROM project_invites WHERE id = ?').bind(invite.id).first<{status:string;accepted_by:string|null}>(),access=await projectAccess(db,parent.id,user.id);
   if(current?.status!=='accepted'||current.accepted_by!==user.id||!access)return fail(409,'참여 한도 또는 기존 역할 때문에 수락하지 못했습니다. 프로젝트 소유자에게 역할 변경을 요청해 주세요.');
   return json({projectId:parent.id,name:parent.name,venue:parent.venue,role:access.role,accepted:true});
  }
  const match=/^\/api\/projects\/([0-9a-f-]{36})\/(members|invitations)(?:\/([0-9a-f-]{36}))?$/.exec(url.pathname);if(!match||!uuidPattern.test(match[1])||match[3]&&!uuidPattern.test(match[3]))return fail(404,'공동 작업 주소를 찾을 수 없습니다.');
  const projectId=match[1],kind=match[2],id=match[3],access=await projectAccess(db,projectId,user.id);if(!access)return fail(404,'프로젝트를 찾을 수 없습니다.');if(access.role!=='owner')return fail(403,'프로젝트 소유자만 참여자와 초대를 관리할 수 있습니다.');
  if(method==='GET'&&!id){if(kind==='members'){const {results}=await db.prepare('SELECT * FROM project_members WHERE project_id = ? ORDER BY revoked, updated_at DESC LIMIT 201').bind(projectId).all<MemberRow>();return json({items:results.slice(0,200).map(member),truncated:results.length>200});}const {results}=await db.prepare('SELECT * FROM project_invites WHERE project_id = ? ORDER BY created_at DESC LIMIT 201').bind(projectId).all<InviteRow>();return json({items:results.slice(0,200).map(invitation),truncated:results.length>200});}
  if(!((kind==='invitations'&&method==='POST'&&!id)||(method==='PATCH'&&id)))return fail(405,'지원하지 않는 공동 작업 요청입니다.');
  if(access.row.archived)return fail(409,'보관된 프로젝트는 복구한 뒤 참여자를 변경해 주세요.');let value;try{value=await body(request);}catch(e){return fail(400,(e as Error).message);}
  if(kind==='invitations'&&method==='POST'&&!id){const invitationId=inviteId(value.id),email=inviteEmail(value.email),role=memberRole(value.role),token=inviteToken(value.token),hash=await inviteTokenHash(token),now=new Date().toISOString(),expires=new Date(Date.now()+INVITE_DURATION_MS).toISOString();
   if(user.email&&email===inviteEmail(user.email))return fail(409,'소유자 자신에게 초대를 만들 수 없습니다.');
   const previous=await db.prepare('SELECT * FROM project_invites WHERE id = ? AND project_id = ?').bind(invitationId,projectId).first<InviteRow>();if(previous)return previous.recipient_email===email&&previous.role===role&&previous.token_hash===hash?json(invitation(previous)):fail(409,'다른 초대에서 사용한 요청 ID입니다.');
   if(await db.prepare('SELECT user_id FROM project_members WHERE project_id = ? AND recipient_email = ? AND revoked = 0').bind(projectId,email).first())return fail(409,'이미 참여한 계정입니다. 참여자 목록에서 역할을 바꿔 주세요.');
   const result=await db.prepare('INSERT INTO project_invites (id, project_id, recipient_email, role, token_hash, revision, status, expires_at, created_at, updated_at) SELECT ?, ?, ?, ?, ?, 1, \'pending\', ?, ?, ? WHERE EXISTS (SELECT 1 FROM cloud_projects WHERE id = ? AND owner_id = ? AND archived = 0) AND (SELECT COUNT(*) FROM project_invites WHERE project_id = ? AND status = \'pending\' AND expires_at > ?) < ? ON CONFLICT(id) DO NOTHING').bind(invitationId,projectId,email,role,hash,expires,now,now,projectId,user.id,projectId,now,PROJECT_INVITE_MAX).run();if(!result.success)throw new Error();if(!result.meta.changes)return fail(409,'진행 중인 초대 한도 또는 다른 요청 때문에 저장하지 못했습니다.');return json(invitation((await db.prepare('SELECT * FROM project_invites WHERE id = ? AND project_id = ?').bind(invitationId,projectId).first<InviteRow>())!),201);
  }
  if(method!=='PATCH'||!id)return fail(405,'지원하지 않는 공동 작업 요청입니다.');const expected=revision(value.expectedRevision),now=new Date().toISOString();
  if(kind==='invitations'){if(value.revoked!==true)return fail(400,'초대 취소만 변경할 수 있습니다.');const result=await db.prepare('UPDATE project_invites SET status = \'revoked\', revision = revision + 1, updated_at = ? WHERE id = ? AND project_id = ? AND revision = ? AND status = \'pending\' AND EXISTS (SELECT 1 FROM cloud_projects WHERE id = ? AND owner_id = ? AND archived = 0)').bind(now,id,projectId,expected,projectId,user.id).run();if(!result.success)throw new Error();return result.meta.changes?json({revoked:true}):fail(409,'초대가 수락/변경되었습니다. 목록을 새로고침해 주세요.');}
  const role=memberRole(value.role);if(typeof value.revoked!=='boolean')return fail(400,'참여 상태가 필요합니다.');if(id===user.id)return fail(403,'소유자 역할은 변경할 수 없습니다.');if(value.revoked===false){const current=await db.prepare('SELECT revoked FROM project_members WHERE project_id = ? AND user_id = ?').bind(projectId,id).first<{revoked:number}>();if(current?.revoked)return fail(409,'제외된 참여자는 새 초대로 다시 참여해야 합니다.');}
  const result=await db.prepare('UPDATE project_members SET role = ?, revoked = ?, revision = revision + 1, updated_at = ? WHERE project_id = ? AND user_id = ? AND revision = ? AND revoked = 0 AND EXISTS (SELECT 1 FROM cloud_projects WHERE id = ? AND owner_id = ? AND archived = 0)').bind(role,value.revoked?1:0,now,projectId,id,expected,projectId,user.id).run();if(!result.success)throw new Error();if(!result.meta.changes)return fail(409,'다른 기기에서 참여자를 변경했습니다. 목록을 새로고침해 주세요.');return json(member((await db.prepare('SELECT * FROM project_members WHERE project_id = ? AND user_id = ?').bind(projectId,id).first<MemberRow>())!));
 }catch(e){return fail(e instanceof SyntaxError||e instanceof CollaborationInputError?400:503,'초대/참여자 작업을 완료하지 못했습니다. 같은 요청으로 다시 시도할 수 있습니다.');}
}
