import {useEffect,useRef,useState} from 'react';
import {X} from 'lucide-react';
import {authClient,initializeAuth,signOut,useAuth} from '../state/auth';
import {authReturnPath} from '../domain/authConfig';
export function AccountDialog({onClose,returnPath}:{onClose:()=>void;returnPath?:string}){
 const redirectPath=authReturnPath(returnPath);
 const ref=useRef<HTMLDialogElement>(null),{status,user,error,config}=useAuth(),[email,setEmail]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[failure,setFailure]=useState('');
 useEffect(()=>{ref.current?.showModal();void initializeAuth();},[]);
 return <dialog ref={ref} className="export-dialog notes-dialog" aria-label="계정 로그인" onCancel={onClose}><div className="dialog-header"><h2>계정</h2><button type="button" className="icon-button" aria-label="계정 창 닫기" onClick={onClose}><X size={18}/></button></div>
 {status==='loading'?<p role="status">계정 연결 확인 중…</p>:status==='disabled'?<p>계정 로그인을 아직 사용할 수 없습니다. 전시는 현재 브라우저에 자동 저장되며 프로젝트 자산 백업으로 옮길 수 있습니다.</p>:status==='error'?<><p role="alert">{error}</p><button className="button secondary" onClick={()=>void initializeAuth()}>연결 다시 확인</button></>:user?<><p>{user.email||'로그인됨'}</p><p className="field-hint">로컬 프로젝트는 로그인만으로 업로드되지 않습니다. 프로젝트 창에서 클라우드 저장을 시작하세요.</p><button className="button secondary" disabled={busy} onClick={async()=>{setBusy(true);setFailure('');try{await signOut();setMessage('로그아웃했습니다. 로컬 프로젝트는 이 브라우저에 남아 있습니다.');}catch(e){setFailure(e instanceof Error?e.message:'로그아웃하지 못했습니다.');}finally{setBusy(false);}}}>로그아웃</button></>:<form onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setFailure('');try{const client=await authClient(),{error}=await client.auth.signInWithOtp({email:email.trim(),options:{emailRedirectTo:location.origin+redirectPath}});if(error)throw error;setMessage('메일로 로그인 링크를 보냈습니다. 같은 브라우저에서 링크를 열어주세요.');}catch(e){setFailure(e instanceof Error?e.message:'로그인 메일을 보내지 못했습니다.');}finally{setBusy(false);}}}><label className="auth-email">이메일<input type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><button type="submit" className="button primary full" disabled={busy}>{busy?'연결 중…':'이메일로 로그인 링크 보내기'}</button>{config?.googleEnabled&&<button type="button" className="button secondary full" disabled={busy} onClick={async()=>{setBusy(true);setFailure('');try{const client=await authClient(),{error}=await client.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin+redirectPath}});if(error)throw error;}catch(e){setFailure(e instanceof Error?e.message:'Google 로그인을 연결하지 못했습니다.');}finally{setBusy(false);}}}>Google로 로그인</button>}</form>}
 {message&&<p role="status">{message}</p>}{failure&&<p className="warning" role="alert">{failure}</p>}
 </dialog>;
}
