import {useState} from 'react';
import {useEditor} from '../state/editor';
import {NumberField} from './Controls';
import type {ArtworkLayout} from '../domain/artworkLayout';

export function ArtworkLayoutControls(){
 const {project,selected,layoutSelectedArtworks}=useEditor();
 const [gap,setGap]=useState(250),[axis,setAxis]=useState<'horizontal'|'vertical'>('horizontal'),[height,setHeight]=useState(1450);
 const works=project.artworks.filter(a=>selected.some(s=>s.type==='artwork'&&s.id===a.id));
 const reason=works.length!==selected.length||works.length<2?'이미지 작품을 두 개 이상 선택하세요.':project.planDraft&&!project.planReference?.calibrated?'도면 축척을 먼저 보정하세요.':works.some(a=>a.locked)?'잠긴 작품을 해제한 뒤 배치하세요.':works.some(a=>a.wallId!==works[0].wallId||(a.wallSide??'front')!==(works[0].wallSide??'front'))?'같은 벽·같은 면의 작품을 선택하세요.':project.artworks.some(a=>a.groupId&&works.some(w=>w.groupId===a.groupId)&&!works.some(w=>w.id===a.id))?'그룹의 작품을 모두 선택하세요.':null;
 const alignments:[string,Extract<ArtworkLayout,{kind:'align'}>['edge']][]=[['왼쪽','left'],['가로 중앙','center-x'],['오른쪽','right'],['상단','top'],['세로 중앙','center-y'],['하단','bottom']];
 return <section className="inspector-section artwork-layout"><h3>작품 정렬·간격</h3><p className="field-hint">액자·매트·회전을 포함한 외곽을 기준으로 배치합니다. 좌우 방향은 벽면도에서 보는 방향입니다.</p>{reason&&<p className="warning" role="status">{reason}</p>}<fieldset disabled={!!reason} className="artwork-layout-fields"><div className="artwork-alignment-grid">{alignments.map(([label,edge])=><button key={edge} className="button secondary" aria-label={`작품 ${label} 정렬`} onClick={()=>layoutSelectedArtworks({kind:'align',edge})}>{label}</button>)}</div><div className="rotation-buttons"><button className="button secondary" onClick={()=>layoutSelectedArtworks({kind:'spacing',axis:'horizontal'})}>가로 등간격</button><button className="button secondary" onClick={()=>layoutSelectedArtworks({kind:'spacing',axis:'vertical'})}>세로 등간격</button></div><p className="field-hint">등간격은 선택 범위의 양 끝을 유지합니다.</p><label className="select-field"><span>간격 방향</span><select aria-label="작품 간격 방향" value={axis} onChange={e=>setAxis(e.target.value as typeof axis)}><option value="horizontal">가로 · 왼쪽부터</option><option value="vertical">세로 · 위에서부터</option></select></label><NumberField label="작품 사이 간격" value={gap} onChange={setGap} min={0} max={50000}/><button className="button outline full" onClick={()=>layoutSelectedArtworks({kind:'spacing',axis,gapMm:gap})}>간격 적용</button><button className="button secondary full" onClick={()=>layoutSelectedArtworks({kind:'center-wall'})}>선택 범위를 벽 중앙으로</button><NumberField label="공통 중심 높이" value={height} min={0} max={20000} onChange={setHeight}/><button className="button outline full" onClick={()=>layoutSelectedArtworks({kind:'center-height',heightMm:height})}>중심 높이 맞춤</button></fieldset><p className="field-hint">전체 배치가 벽 안에 들어올 때 적용됩니다. 그룹의 작품을 정렬하면 그룹을 유지하면서 작품 사이 배치가 바뀝니다.</p></section>;
}
