import {useMemo} from 'react';
import type {PlanPage} from '../lib/planImport';
import type {Project} from '../domain/types';
import {buildAutomaticVenue} from '../domain/automaticVenue';
import {floorWithOpenings,openingSegments} from '../domain/openings';
export function AutomaticVenuePreview({page,onAdopt,disabled}:{page:PlanPage;onAdopt:(p:Project)=>void;disabled:boolean}){
 const draft=useMemo(()=>buildAutomaticVenue(page),[page]);
 const p=draft.project,scale=p?.planReference?.mmPerPixel??1,origin=p?.planReference?.origin??{x:0,z:0},width=p?.planReference?.widthPx??page.widthPx,height=p?.planReference?.heightPx??page.heightPx;
 return <section className="plan-text-analysis"><strong>자동 공간 초안</strong>{p&&<><p>외곽 벽 {p.walls.filter(w=>w.role!=='partition').length}개 · 내부 벽 {p.walls.filter(w=>w.role==='partition').length}개 · 바닥 {(floorWithOpenings(p).areaMm2/1e6).toFixed(1)} m² · 치수 교차 검증 완료</p><svg role="img" aria-label="자동 공간 초안 미리보기" viewBox={`0 0 ${width} ${height}`} style={{width:'100%',maxHeight:300,background:'white'}}><image href={p.planImageUrl??page.imageUrl} width={width} height={height} opacity={.4}/>{p.walls.map(w=><line key={w.id} x1={(w.start.x-origin.x)/scale} y1={(w.start.z-origin.z)/scale} x2={(w.end.x-origin.x)/scale} y2={(w.end.z-origin.z)/scale} stroke={w.role==='partition'?'#b45d16':'#365cf5'} strokeWidth={5}/>)}{openingSegments(p).map(o=><line key={o.id} x1={(o.start.x-origin.x)/scale} y1={(o.start.z-origin.z)/scale} x2={(o.end.x-origin.x)/scale} y2={(o.end.z-origin.z)/scale} stroke="#16816b" strokeWidth={5} strokeDasharray="8 5"/>)}</svg><p>파랑: 바닥 경계 · 주황: 내부 벽 후보 · 초록 점선: 개구부. 가구와 벽의 의미 구분은 아직 완료되지 않았습니다.</p></>}{p?.sourcePlan&&<details><summary>변환 전 원본 도면</summary><img src={p.sourcePlan.imageUrl} alt="변환 전 원본 도면" style={{width:'100%'}}/></details>}{draft.reasons.map(r=><p key={r}>{r}</p>)}{p&&<><p>적용하면 현재 공간과 작품을 이 초안으로 교체합니다. 실행 취소로 복원할 수 있습니다.</p><button className="button primary" disabled={disabled} onClick={()=>onAdopt(structuredClone(p))}>이 공간 초안 적용</button></>}</section>;
}
