import {detectPlanWalls} from '../lib/detectPlanWalls';
import {useEffect,useRef,useState} from 'react';
import type {Project} from '../domain/types';
import type {PlanLabel} from '../domain/planLabels';
import type {WallCandidate} from '../domain/wallCandidates';
import {matchDimensionLines} from '../domain/dimensionLineEvidence';
export function DimensionEvidence({project,label,onSelect}:{project:Project;label:PlanLabel;onSelect:(id:string)=>void}){
 const [lines,setLines]=useState<WallCandidate[]|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const controller=useRef<AbortController|null>(null);
 useEffect(()=>{setLines(project.planAnalysis?.lines??null);setError('');setBusy(false);return()=>controller.current?.abort();},[project.planImageUrl]);
 const matches=lines?matchDimensionLines(project,label,lines):[];
 async function analyze(){controller.current?.abort();const control=new AbortController();controller.current=control;setBusy(true);setError('');setLines(null);try{const result=await detectPlanWalls(project.planImageUrl!,155,0.008,control.signal,1);if(!control.signal.aborted)setLines(result);}catch(e){if(!control.signal.aborted)setError((e as Error).message);}finally{if(!control.signal.aborted)setBusy(false);}}
 const r=project.planReference;
 return <section className="dimension-evidence"><strong>치수선 근거 확인</strong><p>평행선과 양 끝 보조선을 비교합니다. 수평·수직 선과 숫자 자리에서 끊긴 선을 비교하며 화살표 모양은 아직 판독하지 않습니다.</p><button className="button secondary" disabled={busy||!r?.calibrated||!project.planImageUrl} onClick={()=>void analyze()}>{busy?'치수선 분석 중…':'주변 치수선 분석'}</button>{busy&&<button className="button secondary" onClick={()=>{controller.current?.abort();setBusy(false);setError('분석을 취소했습니다.');}}>분석 취소</button>}{error&&<p role="alert">{error}</p>}{lines&&r?.calibrated&&<p role="status">{matches.length?`선과 보조선이 맞는 벽 ${matches.length}개 · 원본 확인 필요`:'맞는 치수선 근거를 찾지 못했습니다. 숫자 밖에서 끊긴 선·작은 도면·부분 치수는 놓칠 수 있습니다.'}</p>}{matches.length>1&&<p>후보가 여러 개입니다. 보조선이 연결되는 실제 벽을 확인하세요.</p>}{matches.map(m=><div key={m.wallId}>{r&&<svg role="img" aria-label={`치수선 근거 ${project.walls.find(w=>w.id===m.wallId)?.name}`} viewBox={`0 0 ${r.widthPx} ${r.heightPx}`} style={{width:'100%',maxHeight:240,background:'white'}}><image href={project.planImageUrl} width={r.widthPx} height={r.heightPx}/>{m.evidence.map(l=><line key={l.id} x1={l.start.x} y1={l.start.y} x2={l.end.x} y2={l.end.y} stroke="#dc811c" strokeWidth={3}/>)}<>{m.gap&&<line x1={m.gap.start.x} y1={m.gap.start.y} x2={m.gap.end.x} y2={m.gap.end.y} stroke="#a43ccc" strokeWidth={3} strokeDasharray="6 5"/>}</><line x1={m.start.x} y1={m.start.y} x2={m.end.x} y2={m.end.y} stroke="#5157ef" strokeWidth={4}/><rect x={label.box.x} y={label.box.y} width={label.box.width} height={label.box.height} fill="none" stroke="#17956b" strokeWidth={2}/></svg>}<p>주황: 치수선·보조선 후보 / 파랑: 연결할 벽{m.gap&&' / 보라 점선: 숫자 자리의 추정 연결 구간'}</p>{m.gap&&<p>숫자 양쪽 선을 하나의 치수선 후보로 묶었습니다. 점선 구간은 원본에서 검출한 선이 아닙니다.</p>}<button className="button secondary" disabled={project.walls.find(w=>w.id===m.wallId)?.locked} onClick={()=>onSelect(m.wallId)}>{project.walls.find(w=>w.id===m.wallId)?.name} 길이 연결</button></div>)}</section>;
}
