import { useEffect, useRef, useState } from 'react';
import { useEditor } from '../state/editor';
import { wallLength } from '../domain/model';
import { artStyle } from '../lib/art';
export function ElevationView() {
  const { project, activeWallId, setActiveWall, selected, select, patchArtwork, showDimensions } = useEditor();
  const wall = project.walls.find(w => w.id === activeWallId) || project.walls[0];
  const svg = useRef<SVGSVGElement>(null);
  const [drag, setDrag] = useState<{ id: string; x: number; y: number; offsetX: number; offsetY: number } | null>(null);
  const [side,setSide]=useState<'front'|'back'>('front');
  const selectedArt=project.artworks.find(a=>selected[0]?.type==='artwork'&&a.id===selected[0].id);
  useEffect(()=>{if(selectedArt)setSide(selectedArt.wallSide??'front');setDrag(null);},[selectedArt?.id,selectedArt?.wallSide,activeWallId]);
  if (!wall) return null;
  const width = wallLength(wall), height = wall.heightMm;
  const arts = project.artworks.filter(a => a.wallId === wall.id && a.visible && (a.wallSide??'front')===side);
  function point(e: React.PointerEvent) { const m = svg.current?.getScreenCTM()?.inverse(); return m ? new DOMPoint(e.clientX, e.clientY).matrixTransform(m) : null; }
  return <div className="drawing-view elevation"><div className="wall-tabs">{project.walls.map(w => <button className={w.id === wall.id ? 'active' : ''} key={w.id} onClick={() => setActiveWall(w.id)}>{w.name}</button>)}</div><div className="wall-face-tabs"><button aria-pressed={side==='front'} onClick={()=>{setSide('front');setDrag(null);}}>A면 보기</button><button aria-pressed={side==='back'} onClick={()=>{setSide('back');setDrag(null);}}>B면 보기</button></div><svg ref={svg} viewBox={`-700 -650 ${width + 1400} ${height + 1600}`} onPointerMove={e => { if (drag) { const p = point(e); if (p) setDrag({ ...drag, x: Math.round((p.x - drag.offsetX) / 10) * 10, y: Math.round((p.y - drag.offsetY) / 10) * 10 }); } }} onPointerUp={() => { if (drag) { patchArtwork(drag.id, { alongMm: side==='back'?width-drag.x:drag.x, centerHeightMm: height - drag.y }); setDrag(null); } }} onPointerCancel={() => setDrag(null)}><rect x="0" y="0" width={width} height={height} fill={wall.color} stroke="#c1c9d2" strokeWidth="12" /><rect x="0" y={height} width={width} height="80" fill="#b9c0c8" />{showDimensions && <g className="svg-dimensions"><line x1="0" y1="-280" x2={width} y2="-280" /><line x1="0" y1="-370" x2="0" y2="-190" /><line x1={width} y1="-370" x2={width} y2="-190" /><text x={width / 2} y="-355" textAnchor="middle">{Math.round(width).toLocaleString()} mm</text><line x1="-280" y1="0" x2="-280" y2={height} /><text x="-370" y={height / 2} textAnchor="middle" transform={`rotate(-90 -370 ${height / 2})`}>{height.toLocaleString()} mm</text></g>}{arts.map(a => {
    const isSelected = selected.some(s => s.id === a.id), x = drag?.id === a.id ? drag.x : (side==='back'?width-a.alongMm:a.alongMm), y = drag?.id === a.id ? drag.y : height - a.centerHeightMm;
    return <g key={a.id} className={a.locked ? 'selectable' : 'draggable-art'} onPointerDown={e => { e.stopPropagation(); select({ type: 'artwork', id: a.id }, e.shiftKey); if (!a.locked && !e.shiftKey) { const p = point(e); if (p) { e.currentTarget.setPointerCapture(e.pointerId); setDrag({ id: a.id, x, y, offsetX: p.x - x, offsetY: p.y - y }); } } }}><rect x={x - a.widthMm / 2 - 25} y={y - a.heightMm / 2 - 25} width={a.widthMm + 50} height={a.heightMm + 50} fill={{ black: '#282827', natural: '#b9a383', white: '#e7e7e4', none: '#eee9dd' }[a.frame]} /><foreignObject x={x - a.widthMm / 2} y={y - a.heightMm / 2} width={a.widthMm} height={a.heightMm} pointerEvents="none"><div style={{ width: '100%', height: '100%', ...artStyle(a.imageUrl) }} /></foreignObject>{isSelected && <rect x={x - a.widthMm / 2 - 45} y={y - a.heightMm / 2 - 45} width={a.widthMm + 90} height={a.heightMm + 90} fill="none" stroke="#365cf5" strokeWidth="20" />}{showDimensions && isSelected && <g className="svg-dimensions blue"><line x1={x} y1={y} x2={x} y2={height + 220} strokeDasharray="30 25" /><text x={x + 120} y={height - 150} textAnchor="start">중심 {Math.round(height - y).toLocaleString()} mm</text><text x={x} y={y - a.heightMm / 2 - 155} textAnchor="middle">{a.widthMm} × {a.heightMm}</text></g>}</g>;
  })}</svg><p className="canvas-hint">{side==='front'?'A면':'B면'} · 작품을 드래그해 높이와 위치를 조정하세요 · Shift로 여러 작품 선택</p></div>;
}
