// @vitest-environment jsdom
import {act,StrictMode} from 'react';
import {createRoot,type Root} from 'react-dom/client';
import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {File as NodeFile,Blob as NodeBlob} from 'node:buffer';
import {IDBFactory} from 'fake-indexeddb';
import {createCanvas,loadImage,type Image as NativeImage,type Canvas} from '@napi-rs/canvas';
import MaterialLibraryDialog from './MaterialLibraryDialog';
import {ArtworkLibraryDialog} from './ArtworkLibraryDialog';
import {LengthUnitContext} from './LengthUnits';
import {useEditor} from '../state/editor';
import {createDemoProject,parseProject} from '../domain/model';
import {materialPreset} from '../domain/materials';
import type {MaterialTemplate} from '../domain/materialLibrary';
import type {Project} from '../domain/types';
import * as materials from '../lib/materialLibrary';
import * as artworks from '../lib/artworkLibrary';
import {materialThumbnail,readMaterialLibraryBackup} from '../lib/materialLibraryMedia';
import {prepareArtworkLibraryInput,readArtworkLibraryBackup} from '../lib/artworkLibraryMedia';
import {downloadBlob} from '../lib/art';

vi.mock('../lib/art',async original=>({...await original<typeof import('../lib/art')>(),downloadBlob:vi.fn()}));
vi.mock('../lib/materialLibraryMedia',async original=>{const actual=await original<typeof import('../lib/materialLibraryMedia')>();return {...actual,materialThumbnail:vi.fn(actual.materialThumbnail),readMaterialLibraryBackup:vi.fn(actual.readMaterialLibraryBackup)};});
vi.mock('../lib/artworkLibraryMedia',async original=>{const actual=await original<typeof import('../lib/artworkLibraryMedia')>();return {...actual,prepareArtworkLibraryInput:vi.fn(actual.prepareArtworkLibraryInput),readArtworkLibraryBackup:vi.fn(actual.readArtworkLibraryBackup)};});
// Operational authentication is deferred; this turn exercises the local panels.
vi.mock('./CloudLibraryPanel',()=>({CloudLibraryPanel:()=>null}));
vi.setConfig({testTimeout:10000});
type Kind='material'|'artwork';
let root:Root,container:HTMLDivElement,p:Project,source:MaterialTemplate,mat:ReturnType<typeof materials.createMaterialLibrary>,art:ReturnType<typeof artworks.createArtworkLibrary>,mid:string,aid:string,imageUrl:string,factory:IDBFactory,matName:string,artName:string;
const close=vi.fn();let releases:Array<()=>void>=[];
function deferred<T>(){let resolve!:(value:T)=>void,reject!:(error:Error)=>void;const promise=new Promise<T>((r,j)=>{resolve=r;reject=j;});return {promise,resolve,reject};}
async function waitUi(assertion:()=>void){const deadline=Date.now()+5000;for(;;){await act(async()=>{await Promise.all([mat.list(),art.list()]);await new Promise(resolve=>setTimeout(resolve,0));});try{assertion();return;}catch(error){if(Date.now()>=deadline)throw error;}}}
async function mount(kind:Kind){await act(async()=>root.render(<StrictMode><LengthUnitContext.Provider value="cm">{kind==='material'?<MaterialLibraryDialog source={source} target={{type:'wall',id:'wall-a'}} onClose={close}/>:<ArtworkLibraryDialog onClose={close}/>}</LengthUnitContext.Provider></StrictMode>));await waitUi(()=>expect(container.textContent).not.toContain(kind==='material'?'재질 처리 중':'작품 처리 중'));}
async function click(label:string){const button=[...container.querySelectorAll<HTMLButtonElement>('button')].find(b=>b.getAttribute('aria-label')===label||b.textContent?.trim()===label)!;expect(button,container.textContent).toBeDefined();expect(button.matches(':disabled'),container.textContent).toBe(false);await act(async()=>button.click());}
async function change(label:string,value:string){const input=container.querySelector<HTMLInputElement|HTMLSelectElement>(`[aria-label="${label}"]`)!;expect(input).toBeDefined();await act(async()=>{Object.getOwnPropertyDescriptor(input instanceof HTMLSelectElement?HTMLSelectElement.prototype:HTMLInputElement.prototype,'value')!.set!.call(input,value);input.dispatchEvent(new Event(input instanceof HTMLSelectElement?'change':'input',{bubbles:true}));});}
async function check(label:string){const input=[...container.querySelectorAll('label')].find(l=>l.textContent?.trim()===label)!.querySelector('input')!;await act(async()=>input.click());}
async function message(fragment:string){await waitUi(()=>expect(container.textContent).toContain(fragment));}
async function upload(kind:Kind,file:File){const input=container.querySelector<HTMLInputElement>(`input[aria-label="${kind==='material'?'재질':'작품'} 라이브러리 백업 파일"]`)!;Object.defineProperty(input,'files',{configurable:true,value:[file]});await act(async()=>input.dispatchEvent(new Event('change',{bubbles:true})));}
const applyLabel=(kind:Kind)=>kind==='material'?'전시 목재 재질 적용':'라이브러리 사진 라이브러리 작품 배치';
async function roundtrip(){await act(async()=>{useEditor.getState().loadProject({...p,id:'other-library-project'});useEditor.getState().loadProject(p);useEditor.getState().notify('다음 작업 알림');});}
beforeEach(async()=>{
 vi.resetAllMocks();releases=[];(globalThis as typeof globalThis&{IS_REACT_ACT_ENVIRONMENT:boolean}).IS_REACT_ACT_ENVIRONMENT=true;vi.stubGlobal('File',NodeFile);vi.stubGlobal('Blob',NodeBlob);
 Object.defineProperty(HTMLDialogElement.prototype,'showModal',{configurable:true,value:function(this:HTMLDialogElement){this.open=true;}});vi.stubGlobal('BroadcastChannel',undefined);
 class ImageAdapter {native?:NativeImage;naturalWidth=0;naturalHeight=0;onload:(()=>void)|null=null;onerror:(()=>void)|null=null;set src(url:string){if(!url)return;void loadImage(url).then(image=>{this.native=image;this.naturalWidth=image.width;this.naturalHeight=image.height;this.onload?.();},()=>this.onerror?.());}}
 vi.stubGlobal('Image',ImageAdapter);const canvases=new WeakMap<HTMLCanvasElement,Canvas>();vi.spyOn(HTMLCanvasElement.prototype,'getContext').mockImplementation(function(this:HTMLCanvasElement,kind:string){if(kind!=='2d')return null;let canvas=canvases.get(this);if(!canvas){canvas=createCanvas(this.width,this.height);canvases.set(this,canvas);const ctx=canvas.getContext('2d'),draw=ctx.drawImage.bind(ctx);ctx.drawImage=((image:ImageAdapter|NativeImage,...args:unknown[])=>Reflect.apply(draw,ctx,[image instanceof ImageAdapter?image.native!:image,...args])) as typeof ctx.drawImage;}return canvas.getContext('2d') as unknown as RenderingContext;} as HTMLCanvasElement['getContext']);vi.spyOn(HTMLCanvasElement.prototype,'toDataURL').mockImplementation(function(this:HTMLCanvasElement,type?:string){return canvases.get(this)!.toDataURL(type==='image/webp'?'image/webp':'image/png');});
 const image=createCanvas(32,16),ctx=image.getContext('2d');ctx.fillStyle='#80c8ff';ctx.fillRect(0,0,32,16);imageUrl=image.toDataURL('image/png');source={name:'전시 목재',category:'architecture',color:'#ffffff',material:{...materialPreset('wood').material,texture:{imageUrl,widthMm:2000,heightMm:1000},normal:{imageUrl,widthMm:500,heightMm:250,strength:1.5}}};
 p={...createDemoProject(),id:'library-workflow',displayUnit:'cm',note:'PRIVATE_PROJECT',scenes:[]};p.walls[0].note='PRIVATE_WALL';p.artworks[0]={...p.artworks[0],imageUrl,name:'라이브러리 사진',artist:'작가 A',year:'2026',medium:'pigment print',note:'PRIVATE_INSTALLATION',rotationDeg:15};useEditor.getState().loadProject(p,true);useEditor.getState().select({type:'artwork',id:p.artworks[0].id});
 factory=new IDBFactory();matName='material-ui-'+crypto.randomUUID();artName='artwork-ui-'+crypto.randomUUID();mat=materials.createMaterialLibrary(factory,matName);art=artworks.createArtworkLibrary(factory,artName);vi.spyOn(materials,'materialLibrary').mockReturnValue(mat);vi.spyOn(artworks,'artworkLibrary').mockReturnValue(art);
 const actualMat=await vi.importActual<typeof import('../lib/materialLibraryMedia')>('../lib/materialLibraryMedia'),actualArt=await vi.importActual<typeof import('../lib/artworkLibraryMedia')>('../lib/artworkLibraryMedia');vi.mocked(materialThumbnail).mockImplementation(actualMat.materialThumbnail);vi.mocked(readMaterialLibraryBackup).mockImplementation(actualMat.readMaterialLibraryBackup);vi.mocked(prepareArtworkLibraryInput).mockImplementation(actualArt.prepareArtworkLibraryInput);vi.mocked(readArtworkLibraryBackup).mockImplementation(actualArt.readArtworkLibraryBackup);
 mid=(await mat.add(source,await materialThumbnail(source))).id;aid=(await art.add(await prepareArtworkLibraryInput('image',p.artworks[0]))).id;container=document.createElement('div');document.body.append(container);root=createRoot(container);
});
afterEach(async()=>{for(const release of releases)release();await act(async()=>{root.unmount();await Promise.all([mat.list(),art.list()]);});container.remove();vi.restoreAllMocks();vi.unstubAllGlobals();});

it.each(['material','artwork'] as const)('rejects a late %s application after project A→B→A',async kind=>{
 const found=kind==='material'?await mat.read(mid):await art.read(aid),job=deferred<typeof found>();if(kind==='material')vi.spyOn(mat,'read').mockImplementationOnce(()=>job.promise as ReturnType<typeof mat.read>);else vi.spyOn(art,'read').mockImplementationOnce(()=>job.promise as ReturnType<typeof art.read>);await mount(kind);await click(applyLabel(kind));await roundtrip();const before=useEditor.getState().project,closed=close.mock.calls.length;await act(async()=>job.resolve(found));expect(useEditor.getState().project).toBe(before);expect(useEditor.getState().message).toBe('다음 작업 알림');expect(close).toHaveBeenCalledTimes(closed);
});

it.each(['material','artwork'] as const)('does not apply a pending %s after unmount',async kind=>{
 const found=kind==='material'?await mat.read(mid):await art.read(aid),job=deferred<typeof found>();if(kind==='material')vi.spyOn(mat,'read').mockImplementationOnce(()=>job.promise as ReturnType<typeof mat.read>);else vi.spyOn(art,'read').mockImplementationOnce(()=>job.promise as ReturnType<typeof art.read>);await mount(kind);await click(applyLabel(kind));await act(async()=>root.unmount());const before=useEditor.getState().project;await act(async()=>job.resolve(found));expect(useEditor.getState().project).toBe(before);expect(close).not.toHaveBeenCalled();
});

it.each(['material','artwork'] as const)('does not download a late %s backup after unmount',async kind=>{
 const backup=kind==='material'?await mat.backup():await art.backup(),job=deferred<typeof backup>();if(kind==='material')vi.spyOn(mat,'backup').mockImplementationOnce(()=>job.promise as ReturnType<typeof mat.backup>);else vi.spyOn(art,'backup').mockImplementationOnce(()=>job.promise as ReturnType<typeof art.backup>);await mount(kind);await click(kind==='material'?'재질 백업':'라이브러리 백업');await act(async()=>root.unmount());await act(async()=>job.resolve(backup));expect(downloadBlob).not.toHaveBeenCalled();
});

it.each(['material','artwork'] as const)('does not start a %s restore when its decoder finishes after unmount',async kind=>{
 const backup=kind==='material'?await mat.backup():await art.backup(),job=deferred<typeof backup>();if(kind==='material')vi.mocked(readMaterialLibraryBackup).mockImplementationOnce(()=>job.promise as ReturnType<typeof readMaterialLibraryBackup>);else vi.mocked(readArtworkLibraryBackup).mockImplementationOnce(()=>job.promise as ReturnType<typeof readArtworkLibraryBackup>);await mount(kind);await upload(kind,new File(['fixture'],'library.json',{type:'application/json'}));await act(async()=>root.unmount());await act(async()=>job.resolve(backup));expect(await mat.list()).toHaveLength(1);expect(await art.list()).toHaveLength(1);
});

it.each(['material','artwork'] as const)('does not start a %s write after preparation and a project roundtrip',async kind=>{
 const value=kind==='material'?await materialThumbnail(source):await prepareArtworkLibraryInput('image',p.artworks[0]),job=deferred<typeof value>();if(kind==='material')vi.mocked(materialThumbnail).mockImplementationOnce(()=>job.promise as ReturnType<typeof materialThumbnail>);else vi.mocked(prepareArtworkLibraryInput).mockImplementationOnce(()=>job.promise as ReturnType<typeof prepareArtworkLibraryInput>);await mount(kind);await click(kind==='material'?'재질 저장':'선택 작품 저장');await roundtrip();await act(async()=>job.resolve(value));expect(await mat.list()).toHaveLength(1);expect(await art.list()).toHaveLength(1);
});

it('saves, backs up, restores, archives and applies actual native material assets through the UI and IndexedDB',async()=>{
 await mount('material');await change('저장할 재질 이름','새 마감');await click('재질 저장');await message('현재 재질을 저장했습니다');const saved=(await mat.list()).find(i=>i.name==='새 마감')!;expect((await materials.createMaterialLibrary(factory,matName).read(saved.id))?.template).toEqual({...source,name:'새 마감'});expect(useEditor.getState().project).toEqual(p);
 await click('재질 백업');await message('재질 백업을 저장');const blob=vi.mocked(downloadBlob).mock.calls[0][0],backup=JSON.parse(await blob.text());expect(backup.items).toHaveLength(2);await upload('material',new File([await blob.arrayBuffer()],'restore-material.json',{type:'application/json'}));await message('2개 재질을 새 항목');expect(await mat.list()).toHaveLength(4);expect(new Set((await mat.list()).map(i=>i.id)).size).toBe(4);
 await change('재질 라이브러리 검색','새 마감');expect(container.querySelectorAll('article.material-library-card')).toHaveLength(2);await change('재질 라이브러리 검색','');await click('전시 목재 재질 보관');await message('재질을 보관했습니다');await check('보관된 재질 보기');await click('전시 목재 재질 복구');await message('재질을 복구했습니다');await check('보관된 재질 보기');const before=structuredClone(useEditor.getState().project);await click('새 마감 재질 적용');await waitUi(()=>expect(close).toHaveBeenCalledTimes(1));expect(useEditor.getState().project.walls[0]).toMatchObject({material:source.material,color:source.color,note:'PRIVATE_WALL'});expect(useEditor.getState().project.walls[0].start).toEqual(before.walls[0].start);expect(close).toHaveBeenCalledTimes(1);await act(async()=>useEditor.getState().undo());expect(useEditor.getState().project).toEqual(before);await act(async()=>useEditor.getState().redo());expect(parseProject(useEditor.getState().project)).toEqual(useEditor.getState().project);
});

it('saves portable artwork assets, restores new IDs and installs a new copy on the chosen wall with Undo/Redo',async()=>{
 await mount('artwork');await click('선택 작품 저장');await message('작품을 라이브러리에 저장했습니다');const entries=await art.list();expect(entries).toHaveLength(2);const item=(await artworks.createArtworkLibrary(factory,artName).read(entries[0].id))!;expect(item.template.artwork).toMatchObject({name:'라이브러리 사진',artist:'작가 A',year:'2026',imageUrl,widthMm:900,heightMm:1200});expect(JSON.stringify(item.template)).not.toContain('PRIVATE');expect(item.template.artwork).not.toHaveProperty('rotationDeg');expect(item.template.artwork).not.toHaveProperty('wallId');
 await click('라이브러리 백업');await message('라이브러리 백업을 저장');const blob=vi.mocked(downloadBlob).mock.calls[0][0];await upload('artwork',new File([await blob.arrayBuffer()],'restore-artworks.json',{type:'application/json'}));await message('2개 작품을 새 라이브러리');expect(await art.list()).toHaveLength(4);expect(new Set((await art.list()).map(i=>i.id)).size).toBe(4);await change('라이브러리 작품 검색','작가 A');expect(container.querySelectorAll('article.artwork-library-card')).toHaveLength(4);await click('라이브러리 사진 라이브러리 보관');await message('작품을 보관했습니다');await check('보관된 작품 보기');await click('라이브러리 사진 라이브러리 복구');await message('작품을 복구했습니다');await check('보관된 작품 보기');await change('라이브러리 배치할 벽','wall-b');const before=structuredClone(useEditor.getState().project);await click(applyLabel('artwork'));await waitUi(()=>expect(close).toHaveBeenCalledTimes(1));const state=useEditor.getState(),copy=state.project.artworks.at(-1)!;expect(copy).toMatchObject({wallId:'wall-b',imageUrl,name:'라이브러리 사진',artist:'작가 A',note:'',locked:false});expect(copy.rotationDeg??0).toBe(0);expect(copy.id).not.toBe(p.artworks[0].id);expect(state.project.note).toBe('PRIVATE_PROJECT');expect(state.selected).toEqual([{type:'artwork',id:copy.id}]);expect(state.past).toHaveLength(1);expect(close).toHaveBeenCalledTimes(1);await act(async()=>useEditor.getState().undo());expect(useEditor.getState().project).toEqual(before);await act(async()=>useEditor.getState().redo());expect(useEditor.getState().project.artworks.at(-1)).toEqual(copy);expect(parseProject(state.project)).toEqual(state.project);
});

it.each(['material','artwork'] as const)('rejects a %s backup containing damaged native image bytes without inserting any rows',async kind=>{
 const backup=kind==='material'?await mat.backup():await art.backup();const broken='data:image/png;base64,'+Buffer.from(imageUrl.split(',')[1],'base64').subarray(0,30).toString('base64');if(kind==='material')(backup as materials.MaterialLibraryBackup).items[0].template.material.texture!.imageUrl=broken;else{const template=(backup as artworks.ArtworkLibraryBackup).items[0].template;if(template.kind==='image')template.artwork.imageUrl=broken;}await mount(kind);await upload(kind,new File([JSON.stringify(backup)],'damaged.json',{type:'application/json'}));await message('이미지를 읽지 못');expect(await mat.list()).toHaveLength(1);expect(await art.list()).toHaveLength(1);expect(useEditor.getState().project).toEqual(p);expect(close).not.toHaveBeenCalled();
});

it.each(['material','artwork'] as const)('keeps the newest %s list when focus refreshes finish out of order',async kind=>{
 await mount(kind);const old=kind==='material'?await mat.list():await art.list(),job=deferred<typeof old>();if(kind==='material')await mat.archive(mid,true,old[0].revision);else await art.archive(aid,true,old[0].revision);const newest=kind==='material'?await mat.list():await art.list();if(kind==='material')vi.spyOn(mat,'list').mockImplementationOnce(()=>job.promise as ReturnType<typeof mat.list>).mockResolvedValueOnce(newest as Awaited<ReturnType<typeof mat.list>>);else vi.spyOn(art,'list').mockImplementationOnce(()=>job.promise as ReturnType<typeof art.list>).mockResolvedValueOnce(newest as Awaited<ReturnType<typeof art.list>>);
 await act(async()=>{window.dispatchEvent(new Event('focus'));window.dispatchEvent(new Event('focus'));});const label=kind==='material'?'전시 목재 저장 재질':'라이브러리 사진 라이브러리 작품';await waitUi(()=>expect(container.querySelector(`[aria-label="${label}"]`)).toBeNull());await act(async()=>job.resolve(old));expect(container.querySelector(`[aria-label="${label}"]`)).toBeNull();await check(kind==='material'?'보관된 재질 보기':'보관된 작품 보기');expect(container.querySelector(`[aria-label="${label}"]`)).not.toBeNull();
});

it.each(['material','artwork'] as const)('rejects a %s application during a gesture and permits retry after it ends',async kind=>{
 await mount(kind);const before=useEditor.getState().project;await act(async()=>{useEditor.getState().beginOutdoorTime();useEditor.setState({previewProject:before});});await click(applyLabel(kind));await message('이동·회전을 마친 뒤');expect(useEditor.getState().project).toBe(before);expect(useEditor.getState().past).toHaveLength(0);expect(close).not.toHaveBeenCalled();await act(async()=>useEditor.getState().setTool('select'));await waitUi(()=>expect(container.textContent).not.toContain(kind==='material'?'재질 처리 중':'작품 처리 중'));await click(applyLabel(kind));await waitUi(()=>expect(close).toHaveBeenCalledTimes(1));expect(useEditor.getState().past).toHaveLength(1);
});

it.each(['selection','lock'] as const)('retires a pending material application after a batched %s roundtrip',async transition=>{
 const found=await mat.read(mid),job=deferred<typeof found>();vi.spyOn(mat,'read').mockImplementationOnce(()=>job.promise);await mount('material');await click(applyLabel('material'));await act(async()=>{const state=useEditor.getState();if(transition==='selection'){state.select({type:'wall',id:'wall-b'});state.select({type:'artwork',id:p.artworks[0].id});}else{state.patchWall('wall-a',{locked:true});state.patchWall('wall-a',{locked:false});}state.notify('다음 편집 알림');});const before=useEditor.getState().project,closed=close.mock.calls.length;expect(closed).toBe(1);await act(async()=>job.resolve(found));expect(useEditor.getState().project).toBe(before);expect(useEditor.getState().message).toBe('다음 편집 알림');expect(close).toHaveBeenCalledTimes(closed);
});

it.each(['material','artwork'] as const)('preserves an accepted %s database write without continuing the closed dialog',async kind=>{
 const written=deferred<void>(),ack=deferred<void>();releases.push(()=>ack.resolve());if(kind==='material'){const add=mat.add.bind(mat);vi.spyOn(mat,'add').mockImplementationOnce(async(...args)=>{const item=await add(...args);written.resolve();await ack.promise;return item;});}else{const add=art.add.bind(art);vi.spyOn(art,'add').mockImplementationOnce(async(...args)=>{const item=await add(...args);written.resolve();await ack.promise;return item;});}await mount(kind);await click(kind==='material'?'재질 저장':'선택 작품 저장');await act(async()=>written.promise);const before=useEditor.getState().project;await act(async()=>root.unmount());await act(async()=>ack.resolve());expect(kind==='material'?await mat.list():await art.list()).toHaveLength(2);expect(useEditor.getState().project).toBe(before);expect(close).not.toHaveBeenCalled();expect(downloadBlob).not.toHaveBeenCalled();
});
