import {outdoorAppearance} from '../domain/outdoor';
import {NumberField,IconButton} from './Controls';
import {LockKeyhole,UnlockKeyhole} from 'lucide-react';
import {useEditor} from '../state/editor';
import {translatedLight,spotShadowIds,type ExhibitionLight} from '../domain/lighting';
export function LightInspector({light}:{light:ExhibitionLight}){
 const state=useEditor(),patch=(value:Partial<ExhibitionLight>)=>state.patchLight(light.id,value),disabled=light.locked;
 return <><section className="inspector-section"><h3>조명 <IconButton label={disabled?'조명 잠금 해제':'조명 잠금'} active={disabled} onClick={()=>patch({locked:!disabled})}>{disabled?<LockKeyhole size={16}/>:<UnlockKeyhole size={16}/>}</IconButton></h3>
 <label className="select-field"><span>종류</span><select aria-label="조명 종류" disabled={disabled} value={light.kind} onChange={e=>patch({kind:e.target.value as 'spot'|'area'})}><option value="spot">Spot · 스팟</option><option value="area">Area · 면조명</option></select></label>
 <NumberField label="조명 밝기" suffix={light.kind==='spot'?'cd':'cd/m²'} step={1} value={light.intensity} min={0} max={100000} disabled={disabled} onChange={intensity=>patch({intensity})}/>
 <NumberField label="색온도" suffix="K" step={100} min={2700} max={6500} value={light.kelvin} disabled={disabled} onChange={kelvin=>patch({kelvin})}/>
 {light.kind==='spot'?<><NumberField label="조사각" suffix="°" step={1} value={light.beamDeg} min={1} max={150} disabled={disabled} onChange={beamDeg=>patch({beamDeg})}/><NumberField label="가장자리 부드러움" suffix="%" step={1} value={light.penumbra*100} min={0} max={100} disabled={disabled} onChange={value=>patch({penumbra:value/100})}/><NumberField label="조명 도달 거리" value={light.distanceMm} min={0} max={100000} disabled={disabled} onChange={distanceMm=>patch({distanceMm})}/><p className="field-hint">거리 0은 제한 없이 비춥니다.</p><label className="select-field"><span>그림자</span><input type="checkbox" aria-label="조명 그림자" checked={light.shadow} disabled={disabled} onChange={e=>patch({shadow:e.target.checked})}/></label><p className="field-hint">태양을 포함해 빠른 편집은 최대 2개, 미리보기·캡처는 최대 4개의 그림자를 표시합니다.</p>{light.shadow&&light.intensity>0&&!spotShadowIds(state.project.lights??[]).slice(0,outdoorAppearance(state.project.outdoor)?.sunIntensity&&state.project.outdoor?.shadow?3:4).includes(light.id)&&light.visible&&<p className="field-hint">미리보기에서 태양을 포함한 동시 그림자 4개 제한으로 이 조명은 빛만 표시합니다.</p>}</>:<><NumberField label="조명 면 폭" value={light.widthMm} min={1} max={20000} disabled={disabled} onChange={widthMm=>patch({widthMm})}/><NumberField label="조명 면 높이" value={light.heightMm} min={1} max={20000} disabled={disabled} onChange={heightMm=>patch({heightMm})}/><p className="field-hint">면조명은 넓게 비추며 자체 그림자는 없습니다.</p></>}
 <p className="field-hint">색온도와 밝기는 화면에서 배치안을 비교하기 위한 값입니다.</p></section>
 <section className="inspector-section"><h3>조명 위치</h3>{(['x','y','z'] as const).map(axis=><NumberField key={axis} label={`조명 ${axis.toUpperCase()}`} value={light.position[axis]} min={-1000000} max={1000000} disabled={disabled} onChange={value=>patch(translatedLight(light,{...light.position,[axis]:value}))}/>)}</section>
 <section className="inspector-section"><h3>비추는 지점</h3>{(['x','y','z'] as const).map(axis=><NumberField key={axis} label={`조준 ${axis.toUpperCase()}`} value={light.target[axis]} min={-1000000} max={1000000} disabled={disabled} onChange={value=>patch({target:{...light.target,[axis]:value}})}/>)}<p className="field-hint">조명 위치를 이동하면 비추는 방향을 유지합니다. 조준점을 바꾸면 방향이 돌아갑니다.</p></section></>;
}
