import {useEffect,useMemo,useRef,useState} from 'react';
import {Html,Line,PivotControls} from '@react-three/drei';
import {useThree,type ThreeEvent} from '@react-three/fiber';
import {Euler,Quaternion,Vector3,type Group} from 'three';
import {GLTFLoader} from 'three/examples/jsm/loaders/GLTFLoader.js';
import {useEditor} from '../state/editor';
import {modelArtworkMatrix,modelArtworkCorners} from '../domain/modelArtworks';
import {snapMeasurementCorner} from './measurementSnap3d';
import {modelSnapRadius3d} from './modelSnap3d';
import type {ModelArtwork,WorldPoint} from '../domain/types';
import {modelArtworkAnchor} from '../domain/measurements';
import {disposeModelAsset} from '../lib/modelAssetResources';
import {checkModelArtworkBounds,placeModelArtwork} from '../lib/modelArtworkGeometry';

// Each model's geometry and textures are shared by duplicates; node transforms are independent.
const assets=new Map<string,{refs:number;promise:Promise<Group>;scene?:Group;scenes?:Group[]}>();
function acquire(dataUrl:string){let entry=assets.get(dataUrl);if(!entry){const bytes=Uint8Array.from(atob(dataUrl.split(',')[1]),c=>c.charCodeAt(0));entry={refs:0,promise:new GLTFLoader().parseAsync(bytes.buffer,'').then(g=>{owned.scenes=g.scenes;return g.scene;})};assets.set(dataUrl,entry);const owned=entry;void entry.promise.then(scene=>{owned.scene=scene;if(!owned.refs){disposeModelAsset(owned.scenes??scene);owned.scene=undefined;if(assets.get(dataUrl)===owned)assets.delete(dataUrl);}},()=>{if(assets.get(dataUrl)===owned)assets.delete(dataUrl);});}entry.refs++;const owned=entry;return {promise:entry.promise,release:()=>{owned.refs--;setTimeout(()=>{if(!owned.refs&&owned.scene){disposeModelAsset(owned.scenes??owned.scene);if(assets.get(dataUrl)===owned)assets.delete(dataUrl);owned.scene=undefined;}},0);}};}
function Artwork3D({artwork:a}:{artwork:ModelArtwork}){
 const state=useEditor(),{invalidate,camera,size}=useThree(),[source,setSource]=useState<Group|null>(null),[error,setError]=useState(''),[measureHint,setMeasureHint]=useState<Vector3|null>(null);
 const direction=useRef<WorldPoint|undefined>(undefined),alt=useRef(false);
 const selected=state.selected.some(s=>s.type==='modelArtwork'&&s.id===a.id);
 useEffect(()=>{if(!selected)return;const key=(e:KeyboardEvent)=>{alt.current=e.altKey;},pointer=(e:PointerEvent)=>{alt.current=e.altKey;},blur=()=>{alt.current=false;};window.addEventListener('keydown',key);window.addEventListener('keyup',key);window.addEventListener('pointermove',pointer,true);window.addEventListener('blur',blur);return()=>{window.removeEventListener('keydown',key);window.removeEventListener('keyup',key);window.removeEventListener('pointermove',pointer,true);window.removeEventListener('blur',blur);};},[selected]);
 useEffect(()=>{let cancelled=false;setSource(null);setError('');const asset=acquire(a.model.dataUrl);void asset.promise.then(scene=>{if(cancelled)return;try{checkModelArtworkBounds(scene,a.model);scene.traverse(o=>{if('castShadow' in o){o.castShadow=true;o.receiveShadow=true;}});setSource(scene);invalidate();}catch(e){setError(e instanceof Error?e.message:'3D 작품을 표시하지 못했습니다.');}},()=>{if(!cancelled)setError('3D 작품을 표시하지 못했습니다. 모델을 다시 가져오세요.');});return()=>{cancelled=true;asset.release();};},[a.model.dataUrl,a.model.sizeMm,a.model.sourceOffsetM,invalidate]);
 useEffect(()=>()=>{if(useEditor.getState().modelArtworkGesture?.id===a.id)useEditor.getState().finishModelArtworkTransform(true);},[a.id]);
 useEffect(()=>{setMeasureHint(null);},[state.activeTool,state.captureClean,a.position.x,a.position.y,a.position.z,a.rotation.x,a.rotation.y,a.rotation.z,a.widthMm,a.heightMm,a.depthMm]);
 const placed=useMemo(()=>source?placeModelArtwork(a,source):null,[a,source]),matrix=useMemo(()=>modelArtworkMatrix(a),[a.position.x,a.position.y,a.position.z,a.rotation.x,a.rotation.y,a.rotation.z]);
 const box=modelArtworkCorners(a),pairs=[[0,1],[0,2],[0,4],[1,3],[1,5],[2,3],[2,6],[3,7],[4,5],[4,6],[5,7],[6,7]];
 function pick(e:ThreeEvent<PointerEvent>){if(state.activeTool==='pan'||state.activeTool==='draw')return;e.stopPropagation();if(state.activeTool==='measure'){const p=e.altKey?e.point:snapMeasurementCorner(e.object,e.point,e.face?.normal,camera,size)??e.point;state.pickMeasurement(modelArtworkAnchor(state.project,a.id,{x:p.x*1000,y:p.y*1000,z:p.z*1000}),'3d');}else state.select({type:'modelArtwork',id:a.id},e.shiftKey);}
 return <>{placed&&<primitive object={placed} dispose={null} onPointerDown={pick} onPointerMove={(e:ThreeEvent<PointerEvent>)=>{if(state.activeTool==='measure'&&!state.captureClean){e.stopPropagation();setMeasureHint(e.altKey?null:snapMeasurementCorner(e.object,e.point,e.face?.normal,camera,size));}}} onPointerOut={()=>setMeasureHint(null)}/>} {error&&<Html position={[a.position.x/1000,a.position.y/1000,a.position.z/1000]}><span className="dimension-label">{error}</span></Html>}
 {state.activeTool==='measure'&&!state.captureClean&&measureHint&&<Html position={measureHint.toArray()} center style={{pointerEvents:'none'}}><span className="dimension-label" style={{color:'#16816b'}}>⊙ 모서리</span></Html>}
 {selected&&!state.captureClean&&<>{pairs.map(([i,j],k)=><Line key={k} points={[box[i],box[j]].map(p=>[p.x/1000,p.y/1000,p.z/1000]) as [number,number,number][]} color="#365cf5" lineWidth={1.5}/>)}</>}
 {placed&&selected&&!a.locked&&!state.captureClean&&state.selected.filter(s=>s.type==='modelArtwork')[0]?.id===a.id&&['select','move','rotate'].includes(state.activeTool)&&<PivotControls matrix={matrix} autoTransform={false} fixed scale={75} depthTest={false} disableScaling disableSliders disableRotations={state.activeTool!=='rotate'} disableAxes={state.activeTool==='rotate'} userData={{modelArtworkHandle:true}} onDragStart={({component,directions})=>{const d=component==='Arrow'?directions[0]:undefined;direction.current=d?{x:d.x,y:d.y,z:d.z}:undefined;state.beginModelArtworkTransform(a.id);}} onDrag={(_local,_delta,world)=>{if(useEditor.getState().modelArtworkGesture?.id!==a.id)return;const p=new Vector3(),q=new Quaternion(),s=new Vector3();world.decompose(p,q,s);const e=new Euler().setFromQuaternion(q,'XYZ');const position={x:p.x*1000,y:p.y*1000,z:p.z*1000},rotation={x:e.x*180/Math.PI,y:e.y*180/Math.PI,z:e.z*180/Math.PI},d=direction.current;state.updateModelArtworkTransform(position,rotation,d?{toleranceMm:{x:0,y:0,z:0},direction:d,directionToleranceMm:modelSnapRadius3d(camera,position,d,size),bypass:alt.current}:undefined);}} onDragEnd={()=>{direction.current=undefined;state.finishModelArtworkTransform();}}/>}</>;
}
export function ModelArtworks3D(){const state=useEditor(),project=state.previewProject??state.project;return <>{project.modelArtworks?.filter(a=>a.visible).map(a=><Artwork3D key={a.id} artwork={a}/>)}{!state.captureClean&&state.modelArtworkGesture?.guides?.map((g,i)=>{const n=new Vector3(g.normal.x,g.normal.y,g.normal.z),p=new Vector3(g.point.x/1000,g.point.y/1000,g.point.z/1000),t=new Vector3().crossVectors(n,Math.abs(n.y)<.9?new Vector3(0,1,0):new Vector3(1,0,0)).normalize(),u=new Vector3().crossVectors(n,t).normalize();return <group key={i}>{[t,u].map((axis,k)=><Line key={k} points={[p.clone().addScaledVector(axis,-.45).toArray(),p.clone().addScaledVector(axis,.45).toArray()]} color="#16816b" lineWidth={2} depthTest={false} dashed dashSize={.06} gapSize={.04}/>)}<Html position={p.toArray()} style={{pointerEvents:'none'}}><span className="dimension-label">{g.kind==='wall'?'벽면':g.kind==='floor'?'바닥':g.kind==='center'?'중심':'모서리'} 스냅</span></Html></group>;})}</>;}
