import { useRef, useState } from 'react';
import { Box, Plus, Eye, EyeOff, LockKeyhole, PanelTop, Layers, ImagePlus } from 'lucide-react';
import { useEditor } from '../state/editor';
import { artStyle, readImage } from '../lib/art';
export function Outliner() {
  const { project, selected, select, patchWall, patchArtwork, addArtwork, addWall, notify } = useEditor();
  const [tab, setTab] = useState<'all' | 'artwork'>('all');
  const upload = useRef<HTMLInputElement>(null);
  const [busy, setBusy] = useState(false);
  async function uploadArtwork(file: File) {
    setBusy(true);
    try { addArtwork(await readImage(file), file.name.replace(/\.[^.]+$/, '')); }
    catch (e) { notify(e instanceof Error ? e.message : '이미지를 읽지 못했습니다.'); }
    finally { setBusy(false); }
  }
  return <aside className="outliner"><div className="panel-heading"><h1>전시 구성</h1><span className="count">{project.artworks.length}</span></div><div className="segment"><button className={tab === 'all' ? 'selected' : ''} onClick={() => setTab('all')}>공간</button><button className={tab === 'artwork' ? 'selected' : ''} onClick={() => setTab('artwork')}>작품</button></div><div className="entity-list">{tab === 'all' && <section><div className="section-label">ARCHITECTURE<button aria-label="벽 추가" title="벽 추가" onClick={addWall}><Plus size={14} /></button></div>{project.walls.map(wall => <div className={`entity-row ${selected.some(s => s.id === wall.id) ? 'selected' : ''}`} key={wall.id}><button className={`entity-main ${!wall.visible ? 'muted' : ''}`} onClick={e => select({ type: 'wall', id: wall.id }, e.shiftKey)}><PanelTop size={23} strokeWidth={1.2} /><span>{wall.name}</span>{wall.locked && <LockKeyhole size={12} />}</button><button className="row-action" aria-label={`${wall.name} ${wall.visible ? '숨기기' : '보이기'}`} onClick={() => patchWall(wall.id, { visible: !wall.visible })}>{wall.visible ? <Eye size={14} /> : <EyeOff size={14} />}</button></div>)}<div className="floor-row"><Layers size={23} strokeWidth={1.2} /><span>바닥</span><input type="color" aria-label="바닥 색상" value={project.floorColor} onChange={e => useEditor.getState().patchProject({ floorColor: e.target.value })} /></div></section>}<section><div className="section-label">ARTWORK<span>{project.artworks.length}</span></div>{project.artworks.map((art, i) => <div className={`entity-row artwork-row ${selected.some(s => s.id === art.id) ? 'selected' : ''}`} key={art.id}><button className={`entity-main ${!art.visible ? 'muted' : ''}`} onClick={e => select({ type: 'artwork', id: art.id }, e.shiftKey)}><span className="art-thumbnail" style={artStyle(art.imageUrl)} /><span className="entity-text"><strong>{art.name}</strong><small>작품 {String(i + 1).padStart(2, '0')}</small></span>{art.locked && <LockKeyhole size={12} />}</button><button className="row-action" aria-label={`${art.name} ${art.visible ? '숨기기' : '보이기'}`} onClick={() => patchArtwork(art.id, { visible: !art.visible })}>{art.visible ? <Eye size={14} /> : <EyeOff size={14} />}</button></div>)}{project.artworks.length === 0 && <p className="empty-hint">첫 작품을 등록해 전시를 시작하세요.</p>}</section></div><div className="add-art-card"><Box size={19} strokeWidth={1.4} /><strong>작품을 더해보세요</strong><p>이미지와 실제 크기로<br />나만의 전시를 구성하세요.</p><button className="button outline" disabled={busy} onClick={() => upload.current?.click()}><ImagePlus size={16} />{busy ? '이미지 처리 중' : '작품 추가'}</button><button className="text-button" onClick={() => addArtwork()}>예제 작품 추가</button><input type="file" accept="image/png,image/jpeg,image/webp" hidden ref={upload} onChange={e => { const f = e.target.files?.[0]; if (f) void uploadArtwork(f); e.currentTarget.value = ''; }} /></div></aside>;
}
