import {readPlanOcr} from '../lib/readPlanOcr';
import {useEffect,useRef,useState} from 'react';
import type {PlanPage} from '../lib/planImport';
import {detectPlanLabels} from '../domain/planLabels';
export function PlanTextAnalysis({page,onResult,onBusy,auto=true}:{page:PlanPage;auto?:boolean;onResult:(page:PlanPage)=>void;onBusy:(busy:boolean)=>void}){
 const controller=useRef<AbortController|null>(null),runId=useRef(0);const [busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[error,setError]=useState('');
 async function read(mode:'general'|'numbers'='general'){controller.current?.abort();const control=new AbortController();controller.current=control;const id=++runId.current;setBusy(true);onBusy(true);setProgress(0);setError('');try{const texts=await readPlanOcr(page.imageUrl,control.signal,setProgress,mode);if(!control.signal.aborted&&id===runId.current)onResult({...page,textSource:'ocr',labels:mode==='numbers'?[...(page.labels??[]).filter(l=>l.kind!=='dimension'),...detectPlanLabels(texts).filter(l=>l.kind==='dimension')].map((l,i)=>({...l,id:`label-${i+1}`})):detectPlanLabels(texts)});}catch(e){if(!control.signal.aborted&&id===runId.current)setError((e as Error).message);}finally{if(id===runId.current){setBusy(false);onBusy(false);}}}
 useEffect(()=>{if(auto&&page.textSource==='none')void read();return()=>{runId.current++;controller.current?.abort();onBusy(false);};},[page.imageUrl]);
 return <section className="plan-text-analysis"><strong>문자·설비 표기 인식</strong><p>{page.textSource==='pdf-text'?'PDF 텍스트에서':page.textSource==='ocr'?'OCR 문자에서':'표기 확인 대기 ·'} {page.labels?.length??0}개 후보 · 모두 위치·종류 확인 필요</p>{busy?<><p role="status">도면 문자 읽는 중 {Math.round(progress)}%</p><button className="button secondary" onClick={()=>{controller.current?.abort();runId.current++;setBusy(false);onBusy(false);setError('문자 인식을 취소했습니다. 설비 유무는 확인되지 않았습니다.');}}>문자 인식 취소</button></>:<div className="region-actions"><button className="button secondary" onClick={()=>void read()}>문자 다시 읽기</button><button className="button secondary" onClick={()=>void read('numbers')}>숫자 정밀 다시 읽기</button></div>}{error&&<p role="alert">{error}</p>}<small>상자는 표기의 위치입니다. 설비 크기·벽 높이·설치 제한 범위를 자동 확정하지 않습니다. 숫자 정밀 읽기는 최대 2배 확대·3600px로 읽습니다. 흐린 원본 복원을 보장하지 않습니다. 회전·자르기 후 다시 읽으면 결과가 달라질 수 있습니다.</small></section>;
}
