import {PlanAutoAnalysis} from './PlanAutoAnalysis';
import { useEffect, useRef, useState } from 'react';
import { PlanRegionEditor } from './PlanRegionEditor';
import { loadPlanFile } from '../lib/planImport';
type Loaded = Awaited<ReturnType<typeof loadPlanFile>>;
type Rendered = Awaited<ReturnType<Loaded['renderPage']>>;
export function PlanImportDialog({file,onClose,onImport}:{file:File;onClose:()=>void;onImport:(image:Rendered)=>void}) {
 const [document,setDocument]=useState<Loaded|null>(null),[page,setPage]=useState(1),[preview,setPreview]=useState<Rendered|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(true);
 const [detail,setDetail]=useState(false),[magnified,setMagnified]=useState(false);
 const [reading,setReading]=useState(false);
 const [source,setSource]=useState<Rendered|null>(null),[editing,setEditing]=useState(false);
 const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{dialog.current?.showModal();},[]);
 const generation=useRef(0);
 useEffect(()=>{let cancelled=false;let loaded:Loaded|undefined;void loadPlanFile(file).then(value=>{loaded=value;if(cancelled){void value.destroy();return;}setDocument(value);}).catch(e=>{if(!cancelled){setError(e.message);setBusy(false);}});return()=>{cancelled=true;generation.current++;if(loaded)void loaded.destroy();};},[file]);
 useEffect(()=>{if(!document)return;const revision=++generation.current;setBusy(true);setPreview(null);setError('');void document.renderPage(page,detail).then(value=>{if(revision===generation.current){setPreview(value);setSource(value);setEditing(false);}}).catch(e=>{if(revision===generation.current)setError(e.message);}).finally(()=>{if(revision===generation.current)setBusy(false);});},[document,page,detail]);
 return <dialog ref={dialog} onCancel={onClose} className="export-dialog plan-import-dialog" aria-label="도면 가져오기"><h2>도면 가져오기</h2><p>{file.name}</p>{document&&document.pageCount>1&&<label>PDF 페이지 <select aria-label="PDF 페이지" value={page} disabled={busy||reading} onChange={e=>setPage(Number(e.target.value))}>{Array.from({length:document.pageCount},(_,i)=><option key={i} value={i+1}>{i+1} / {document.pageCount}</option>)}</select></label>}{document&&(file.type==='application/pdf'||/\.pdf$/i.test(file.name))&&<label className="detail-toggle"><input type="checkbox" checked={detail} disabled={busy||reading} onChange={e=>setDetail(e.target.checked)}/>고해상도 렌더 (PDF 최대 4800px)</label>}{busy&&<p role="status">도면을 불러오는 중입니다…</p>}{error&&<p role="alert">{error}</p>}{preview&&<><div className="region-actions"><button className="button secondary" disabled={busy||reading} onClick={()=>setEditing(!editing)}>{editing?'미리보기로 돌아가기':'회전 / 영역 선택'}</button><button className="button secondary" disabled={busy||reading||preview===source} onClick={()=>{setPreview(source);setEditing(false);}}>원래 페이지로</button></div>{editing?<PlanRegionEditor key={`${preview.widthPx}-${preview.heightPx}-${preview.imageUrl.length}`} page={preview} onChange={setPreview} onBusy={setBusy}/>:<><div className="preview-actions"><span>{preview.widthPx} × {preview.heightPx}px</span><button className="button secondary" onClick={()=>setMagnified(!magnified)}>{magnified?'페이지 맞춤':'100% 픽셀 확인'}</button></div><div className={magnified?'plan-preview-scroll magnified':'plan-preview-scroll'}><img className="plan-import-preview" style={magnified?{width:preview.widthPx,maxHeight:'none',maxWidth:'none'}:undefined} src={preview.imageUrl} alt={`가져올 도면 ${page}페이지`} /></div></>}<PlanAutoAnalysis page={preview} onResult={value=>{setPreview(current=>current?.imageUrl===value.imageUrl?value:current);setSource(current=>current?.imageUrl===value.imageUrl?value:current);}} onBusy={setReading}/>{preview.diagnostics?.warnings.map((warning,i)=><p className="plan-quality-warning" key={i}>{warning}</p>)}<p className="quality-disclaimer">이 안내는 입력 품질 확인용입니다. 벽이나 치수의 인식 정확도를 보장하지 않습니다. 스캔은 확대해도 원본의 흐림이 복원되지 않습니다.</p></>}<p>페이지를 배치한 뒤 두 점의 실제 길이로 축척을 맞추세요.</p><div className="dialog-actions"><button className="button secondary" onClick={onClose}>취소</button><button className="button primary" disabled={!preview||busy||reading} onClick={()=>preview&&onImport(preview)}>이 도면 배치</button></div></dialog>;
}
