import {useEffect,useRef,useState} from 'react';
import {X} from 'lucide-react';
import {createCollaborationClient} from '../lib/collaborationClient';
import {newInviteToken,inviteEmail,projectRoleLabels,type MemberRole,type ProjectMember,type ProjectInvitation} from '../domain/collaboration';
import {cloudSession,useAuth} from '../state/auth';
export default function ProjectCollaborationDialog({projectId,name,onClose}:{projectId:string;name:string;onClose:()=>void}){
 const auth=useAuth(),identity=auth.user?.id,context=projectId+':'+identity,live=useRef(context);live.current=context;
 const ref=useRef<HTMLDialogElement>(null),mounted=useRef(false),controller=useRef<AbortController|null>(null),working=useRef(false),draft=useRef<{id:string;email:string;role:MemberRole;token:string}|undefined>(undefined);
 const [data,setData]=useState<{context:string;members:ProjectMember[];invitations:ProjectInvitation[];truncated:boolean}>(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[email,setEmail]=useState(''),[role,setRole]=useState<MemberRole>('viewer'),[link,setLink]=useState<{context:string;url:string}>(),[copied,setCopied]=useState(false);
 useEffect(()=>{mounted.current=true;ref.current?.showModal();return()=>{mounted.current=false;controller.current?.abort();};},[]);
 useEffect(()=>{controller.current?.abort();working.current=false;setData(undefined);setLink(undefined);setError('');draft.current=undefined;void run();return()=>controller.current?.abort();},[context]); // eslint-disable-line react-hooks/exhaustive-deps
 async function run(action?:(client:ReturnType<typeof createCollaborationClient>,guard:()=>void)=>Promise<void>){if(working.current||!identity)return;working.current=true;const c=new AbortController(),captured=context;controller.current=c;setBusy(true);setError('');const guard=()=>{if(!mounted.current||c.signal.aborted||live.current!==captured||useAuth.getState().user?.id!==identity)throw new Error('계정이 바뀌어 공동 작업을 취소했습니다.');};
  try{const session=await cloudSession();guard();if(session.userId!==identity)throw new Error('로그인 계정이 바뀌었습니다.');const client=createCollaborationClient(session.token,fetch,c.signal);await action?.(client,guard);guard();const [members,invitations]=await Promise.all([client.members(projectId),client.invitations(projectId)]);guard();setData({context:captured,members:members.items,invitations:invitations.items,truncated:members.truncated||invitations.truncated});}catch(e){if(mounted.current&&!c.signal.aborted&&live.current===captured)setError(e instanceof Error?e.message:'공동 작업을 완료하지 못했습니다.');}finally{if(mounted.current&&controller.current===c){working.current=false;setBusy(false);}}
 }
 async function create(){let recipient;try{recipient=inviteEmail(email);}catch(e){setError((e as Error).message);return;}if(!draft.current||draft.current.email!==recipient||draft.current.role!==role)draft.current={id:crypto.randomUUID(),email:recipient,role,token:newInviteToken()};const value=draft.current;await run(async(client,guard)=>{const result=await client.invite(projectId,value);guard();if(result.status!=='pending')throw new Error('이미 처리된 초대입니다. 새 초대를 만들어 주세요.');setLink({context,url:location.origin+'/join/'+value.id+'#token='+value.token});setCopied(false);draft.current=undefined;});}
 const rows=data?.context===context?data:undefined,visibleLink=link?.context===context?link.url:undefined;
 return <dialog ref={ref} className="export-dialog notes-dialog" aria-label="프로젝트 공동 작업" onCancel={onClose}><div className="dialog-header"><h2>{name} · 공동 작업</h2><button className="icon-button" aria-label="공동 작업 닫기" onClick={onClose}><X size={18}/></button></div>
 <p className="warning">초대한 계정은 작품·이미지·3D 자산·내부 설치 메모·사진을 포함한 비공개 프로젝트 전체를 읽습니다. 공개된 잠금 공유 링크와 별도 권한입니다.</p>
 <p className="field-hint">편집자는 배치를 저장하고 의견을 작성합니다. 열람자는 읽기만, 댓글 참여자는 읽기와 의견 작성만 가능합니다. 보관·역할·초대 관리는 소유자만 할 수 있습니다. 실시간 동시 편집은 지원하지 않으며 저장 충돌 때 복사본을 보존합니다.</p>
 <form onSubmit={e=>{e.preventDefault();void create();}}><label>초대할 계정 이메일<input type="email" required maxLength={254} value={email} disabled={busy} onChange={e=>setEmail(e.target.value)}/></label><label>참여 역할<select value={role} disabled={busy} onChange={e=>setRole(e.target.value as MemberRole)}>{(['viewer','editor','commenter'] as const).map(r=><option key={r} value={r}>{projectRoleLabels[r]}</option>)}</select></label><button className="button primary" disabled={busy}>7일 유효 초대 링크 만들기</button></form>
 {visibleLink&&<div><p>이 링크를 직접 전달하세요. 지정한 이메일 계정만 수락할 수 있습니다. 닫기 전에 복사해 주세요.</p><input aria-label="새 초대 링크" readOnly value={visibleLink}/><button className="button secondary" onClick={async()=>{try{await navigator.clipboard.writeText(visibleLink);setCopied(true);}catch{setError('위 링크를 직접 선택해 복사해 주세요.');}}}>{copied?'복사됨':'초대 링크 복사'}</button></div>}
 <button className="button secondary" disabled={busy} onClick={()=>void run()}>참여자 목록 새로고침</button>{busy&&<p role="status">공동 작업 처리 중…</p>}{error&&<p className="warning" role="alert">{error}</p>}{rows?.truncated&&<p>최근 기록 200개를 표시합니다.</p>}
 <h3>참여자</h3>{rows?.members.map(m=><article className="project-card" key={m.userId}><strong>{m.email}</strong>{m.revoked?<p>참여 제외됨 · 다시 참여하려면 새 초대가 필요합니다.</p>:<><label>역할<select aria-label={m.email+' 역할'} disabled={busy} value={m.role} onChange={e=>void run(async client=>{await client.changeMember(projectId,m.userId,m.revision,e.target.value as MemberRole,false);})}>{(['viewer','editor','commenter'] as const).map(r=><option key={r} value={r}>{projectRoleLabels[r]}</option>)}</select></label><button className="button secondary" disabled={busy} onClick={()=>void run(async client=>{await client.changeMember(projectId,m.userId,m.revision,m.role,true);})}>참여 제외</button></>}</article>)}
 <h3>초대 기록</h3>{rows?.invitations.map(i=><article className="project-card" key={i.id}><strong>{i.email}</strong><p>{projectRoleLabels[i.role]} · {i.status==='accepted'?'수락됨':i.status==='revoked'?'취소됨':Date.parse(i.expiresAt)<=Date.now()?'만료됨':'수락 대기'} · {new Date(i.expiresAt).toLocaleString('ko-KR')}</p>{i.status==='pending'&&<button className="button secondary" disabled={busy} onClick={()=>void run(async client=>{await client.revokeInvite(projectId,i);})}>초대 취소</button>}</article>)}
 </dialog>;
}
