// @vitest-environment jsdom
import {act,StrictMode} from 'react';
import {createRoot,type Root} from 'react-dom/client';
import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {IDBFactory,IDBObjectStore} from 'fake-indexeddb';
import {createCanvas} from '@napi-rs/canvas';
import {testVenueModel} from '../lib/venueModelTestFixture';
import {ProjectsDialog} from './ProjectsDialog';
import ProjectArchiveDialog from './ProjectArchiveDialog';
import {useEditor,startAutosave,captureAutosaveFlush} from '../state/editor';
import {useAuth} from '../state/auth';
import {createDemoProject,parseProject} from '../domain/model';
import {appendSceneSnapshot} from '../domain/sceneSnapshot';
import {materialPreset} from '../domain/materials';
import {newLight} from '../domain/lighting';
import type {Project} from '../domain/types';
import * as libraries from '../lib/projectLibrary';
import {saveNewLocalProject,writeDraft,readDraft,localProjectRevision} from '../lib/persistence';
vi.mock('./CloudProjectsPanel',()=>({CloudProjectsPanel:()=>null}));
vi.mock('./AccountDialog',()=>({AccountDialog:()=>null}));
// GPU preview and account operations are separate; archive records use real components.
vi.mock('./PresentationMode',()=>({default:()=>null}));
vi.setConfig({testTimeout:10000});
let root:Root,container:HTMLDivElement,p:Project,old:Project,repo:ReturnType<typeof libraries.createProjectLibrary>,factory:IDBFactory,dbName:string,stop:()=>void,writer:ReturnType<typeof vi.fn<(project:Project)=>Promise<void>>>;
let releases:Array<()=>void>=[];const close=vi.fn(),reused=vi.fn();
function deferred<T>(){let resolve!:(v:T)=>void;const promise=new Promise<T>(r=>resolve=r);return {promise,resolve};}
function gate<T>(){const job=deferred<T>();return job;}
async function waitUi(assertion:()=>void){const deadline=Date.now()+5000;for(;;){await act(async()=>{await repo.list();await new Promise(r=>setTimeout(r,0));});try{assertion();return;}catch(error){if(Date.now()>=deadline)throw error;}}}
async function mount(archive=false){await act(async()=>root.render(<StrictMode>{archive?<ProjectArchiveDialog onClose={close} onReused={reused}/>:<ProjectsDialog onClose={close}/>}</StrictMode>));await waitUi(()=>{expect(container.textContent).toContain(p.name);expect(container.textContent).not.toMatch(/프로젝트 처리 중|아카이브를 읽는 중/);});}
async function click(label:string,scope:ParentNode=container){const b=[...scope.querySelectorAll<HTMLButtonElement>('button')].find(b=>b.getAttribute('aria-label')===label||b.textContent?.trim()===label)!;expect(b,container.textContent).toBeDefined();expect(b.matches(':disabled'),container.textContent).toBe(false);await act(async()=>b.click());}
async function changeLabel(label:string,value:string){const el=[...container.querySelectorAll('label')].find(l=>l.textContent?.startsWith(label))!,input=el.querySelector<HTMLInputElement|HTMLSelectElement>('input,select')!;await act(async()=>{Object.getOwnPropertyDescriptor(input instanceof HTMLSelectElement?HTMLSelectElement.prototype:HTMLInputElement.prototype,'value')!.set!.call(input,value);input.dispatchEvent(new Event(input instanceof HTMLSelectElement?'change':'input',{bubbles:true}));});}
async function changeAria(label:string,value:string){const input=container.querySelector<HTMLInputElement>(`[aria-label="${label}"]`)!;await act(async()=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')!.set!.call(input,value);input.dispatchEvent(new Event('input',{bubbles:true}));});await act(async()=>input.dispatchEvent(new FocusEvent('focusout',{bubbles:true})));}
async function check(label:string){const input=[...container.querySelectorAll('label')].find(l=>l.textContent?.trim()===label)!.querySelector('input')!;await act(async()=>input.click());}
const card=()=>[...container.querySelectorAll<HTMLElement>('article.project-card')].find(c=>c.textContent?.includes(old.name))!;
async function selectArchive(){const item=[...container.querySelectorAll<HTMLButtonElement>('button.archive-list-item')].find(b=>b.querySelector('strong')?.textContent===old.name)!;await act(async()=>item.click());await waitUi(()=>expect(container.querySelector('.archive-detail h3')?.textContent).toBe(old.name));}
async function roundtrip(){await act(async()=>{useEditor.getState().loadProject({...p,id:'intermediate-project'});useEditor.getState().loadProject(p);useEditor.getState().notify('다음 작업');});}
beforeEach(async()=>{
 vi.resetAllMocks();releases=[];(globalThis as typeof globalThis&{IS_REACT_ACT_ENVIRONMENT:boolean}).IS_REACT_ACT_ENVIRONMENT=true;Object.defineProperty(HTMLDialogElement.prototype,'showModal',{configurable:true,value:function(this:HTMLDialogElement){this.open=true;}});useAuth.setState({status:'disabled',user:null,config:null,error:''});factory=new IDBFactory();dbName='project-ui-'+crypto.randomUUID();repo=libraries.createProjectLibrary(factory,dbName);vi.spyOn(libraries,'projectLibrary').mockReturnValue(repo);
 p={...createDemoProject(),id:crypto.randomUUID(),name:'편집 중 전시',scenes:[],note:'PRIVATE_CURRENT'};old={...createDemoProject(),id:crypto.randomUUID(),name:'지난 전시',displayUnit:'cm',note:'PRIVATE_ARCHIVE'};const canvas=createCanvas(32,16),ctx=canvas.getContext('2d');ctx.fillStyle='#80c8ff';ctx.fillRect(0,0,32,16);const imageUrl=canvas.toDataURL('image/png');old.artworks[0].imageUrl=imageUrl;old.noteDetails={checklist:[{id:'print',text:'출력 완료',done:true}],images:[{id:'site',name:'현장 참고.png',imageUrl}]};old.referenceModel={...testVenueModel(),note:'PRIVATE_MODEL'};old.walls[0].material=materialPreset('wood').material;old.lights=[newLight(old,'spot')];old=appendSceneSnapshot(old,old,'지난 Scene');old.artworks[0].name='현재 배치 작품';old.scenes[0].artworks[0].name='과거 Scene 작품';await repo.save(old,0,false);await saveNewLocalProject(p);useEditor.getState().loadProject(p,true);writer=vi.fn(writeDraft);stop=startAutosave(writer,60000);container=document.createElement('div');document.body.append(container);root=createRoot(container);
});
afterEach(async()=>{for(const release of releases)release();await act(async()=>root.unmount());container.remove();const finish=captureAutosaveFlush();stop();await finish().catch(()=>{});vi.restoreAllMocks();});

it('creates a saved 12m × 8m outdoor project through unit inputs without losing the current draft',async()=>{
 await mount();await act(async()=>useEditor.getState().renameProject('저장할 최신 작업'));await click('새 프로젝트');await changeLabel('프로젝트 이름','야외 신작');await changeLabel('전시장 이름','야외 별관');await changeLabel('치수 단위','m');await changeAria('초기 공간 너비','12');await changeAria('초기 공간 깊이','8');await changeAria('벽 높이','4');await check('야외 전시');await click('프로젝트 만들기');await waitUi(()=>expect(useEditor.getState().project.name).toBe('야외 신작'));const next=useEditor.getState().project;expect(next.displayUnit).toBe('m');expect(next.outdoor?.mode).toBe('outdoor');expect(Math.hypot(next.walls[0].end.x-next.walls[0].start.x,next.walls[0].end.z-next.walls[0].start.z)).toBe(12000);expect(next.walls[0].heightMm).toBe(4000);expect(next.artworks).toHaveLength(0);expect((await repo.read(p.id))?.project.name).toBe('저장할 최신 작업');expect((await libraries.createProjectLibrary(factory,dbName).read(next.id))?.project).toEqual(next);expect(await readDraft()).toEqual(next);expect(localProjectRevision(next.id)).toBe(1);expect(close).toHaveBeenCalledTimes(1);
});
it('opens a saved project only after preserving the dirty current project',async()=>{await mount();await act(async()=>useEditor.getState().renameProject('저장한 현재 작업'));await click('열기',card());await waitUi(()=>expect(useEditor.getState().project.id).toBe(old.id));expect((await repo.read(p.id))?.project.name).toBe('저장한 현재 작업');expect(await readDraft()).toEqual(old);expect(useEditor.getState().past).toHaveLength(0);expect(close).toHaveBeenCalledTimes(1);});
it('duplicates all stored data under a new ID and preserves the source record and cloud link',async()=>{await repo.saveCloudLink({userId:'11111111-1111-4111-8111-111111111111',localProjectId:old.id,cloudProjectId:crypto.randomUUID(),revision:1,localRevision:1,autoSync:true});const original=await repo.read(old.id);await mount();await click('지난 전시 복제');await waitUi(()=>expect(useEditor.getState().project.name).toBe('지난 전시 복사본'));const copy=useEditor.getState().project;expect({...copy,id:old.id,name:old.name}).toEqual(old);expect(await repo.read(old.id)).toEqual(original);expect(await repo.cloudLink('11111111-1111-4111-8111-111111111111',copy.id)).toBeUndefined();expect(await readDraft()).toEqual(copy);});
it('archives and restores a project while retaining its assets and the active current project',async()=>{await mount();expect(container.querySelector('[aria-label="편집 중 전시 보관"]')?.matches(':disabled')).toBe(true);await click('지난 전시 보관');await waitUi(()=>expect(card()).toBeUndefined());await check('보관된 프로젝트 보기');expect(card()).toBeDefined();await click('지난 전시 복구');await waitUi(()=>expect(card()).toBeUndefined());await check('보관된 프로젝트 보기');expect(card()).toBeDefined();expect((await repo.read(old.id))?.project).toEqual(old);expect(await repo.activeId()).toBe(p.id);expect(useEditor.getState().project).toEqual(p);expect(close).not.toHaveBeenCalled();});

it.each(['unmount','roundtrip'] as const)('does not open a deferred stored project after %s',async transition=>{await mount();const found=await repo.read(old.id),job=gate<typeof found>();vi.spyOn(repo,'read').mockImplementationOnce(()=>job.promise);await click('열기',card());if(transition==='unmount')await act(async()=>root.unmount());else await roundtrip();const before=useEditor.getState().project,closed=close.mock.calls.length;await act(async()=>job.resolve(found));await act(async()=>{await repo.list();await new Promise(r=>setTimeout(r,0));});expect(useEditor.getState().project).toBe(before);expect(await repo.activeId()).toBe(p.id);expect(close).toHaveBeenCalledTimes(closed);});
it('does not start a duplicate write after a project roundtrip during stored read',async()=>{await mount();const found=await repo.read(old.id),job=gate<typeof found>();vi.spyOn(repo,'read').mockImplementationOnce(()=>job.promise);await click('지난 전시 복제');await roundtrip();const before=useEditor.getState().project;await act(async()=>job.resolve(found));await act(async()=>{await repo.list();await new Promise(r=>setTimeout(r,0));});expect(await repo.list()).toHaveLength(2);expect(useEditor.getState().project).toBe(before);expect(useEditor.getState().message).toBe('다음 작업');});
it('retains same-project edits made while an open is waiting and allows a later retry',async()=>{await mount();const found=await repo.read(old.id),job=gate<typeof found>();vi.spyOn(repo,'read').mockImplementationOnce(()=>job.promise);await click('열기',card());await act(async()=>useEditor.getState().renameProject('읽는 중 추가 수정'));await act(async()=>job.resolve(found));await waitUi(()=>expect(container.textContent).toContain('작업이 변경'));expect(useEditor.getState().project.name).toBe('읽는 중 추가 수정');expect(await repo.activeId()).toBe(p.id);expect(close).not.toHaveBeenCalled();await waitUi(()=>expect(container.textContent).not.toContain('프로젝트 처리 중'));await click('열기',card());await waitUi(()=>expect(useEditor.getState().project.id).toBe(old.id));expect((await repo.read(p.id))?.project.name).toBe('읽는 중 추가 수정');});
it('rejects project switching during a transform',async()=>{await mount();await act(async()=>useEditor.setState({previewProject:p}));await click('열기',card());await waitUi(()=>expect(container.textContent).toContain('이동·회전'));expect(useEditor.getState().project.id).toBe(p.id);expect(await repo.activeId()).toBe(p.id);expect(close).not.toHaveBeenCalled();});
it('does not switch or insert a partial duplicate when storage fails',async()=>{await mount();const put=IDBObjectStore.prototype.put;vi.spyOn(IDBObjectStore.prototype,'put').mockImplementation(function(this:IDBObjectStore,value,key){if(this.name==='summaries')throw new DOMException('저장 공간 부족','QuotaExceededError');return put.call(this,value,key);});await click('지난 전시 복제');await waitUi(()=>expect(container.textContent).toContain('저장 공간 부족'));expect(useEditor.getState().project.id).toBe(p.id);expect(await repo.list()).toHaveLength(2);expect(await repo.activeId()).toBe(p.id);expect(close).not.toHaveBeenCalled();});
it('does not activate a staged duplicate if its write acknowledgement arrives after unmount',async()=>{await mount();const written=gate<void>(),ack=gate<void>();releases.push(()=>ack.resolve());const save=repo.save.bind(repo);vi.spyOn(repo,'save').mockImplementationOnce(async(...args)=>{const value=await save(...args);written.resolve();await ack.promise;return value;});await click('지난 전시 복제');await act(async()=>written.promise);await act(async()=>root.unmount());await act(async()=>ack.resolve());expect(await repo.list()).toHaveLength(3);expect(await repo.activeId()).toBe(p.id);expect(useEditor.getState().project.id).toBe(p.id);expect(close).not.toHaveBeenCalled();});

it('browses archived Scene records and reuses all data in a saved new project without changing the archived source',async()=>{await repo.archive(old.id,true,1);const original=await repo.read(old.id);await mount(true);await selectArchive();expect(useEditor.getState().project).toEqual(p);await changeLabel('기록 배치',old.scenes[0].id);await click('작품 배치');expect(container.querySelector('.archive-detail')?.textContent).toContain('과거 Scene 작품');expect(container.querySelector('.archive-detail')?.textContent).not.toContain('현재 배치 작품');await click('메모');expect(container.textContent).toContain('PRIVATE_ARCHIVE');await changeLabel('새 프로젝트 이름','원본 보존 재사용');await click('새 프로젝트로 재사용');await waitUi(()=>expect(reused).toHaveBeenCalledTimes(1));const next=useEditor.getState().project;expect({...next,id:old.id,name:old.name}).toEqual(old);expect(next.id).not.toBe(old.id);expect(next.name).toBe('원본 보존 재사용');expect(await repo.read(old.id)).toEqual(original);expect(await readDraft()).toEqual(next);expect(parseProject(next)).toEqual(next);});
it('rejects archive reuse after a project A→B→A while the current draft is saving',async()=>{await mount(true);await selectArchive();const job=gate<void>(),started=gate<void>();releases.push(()=>job.resolve());writer.mockImplementationOnce(async value=>{started.resolve();await job.promise;await writeDraft(value);});await act(async()=>useEditor.getState().renameProject('재사용 전 저장'));await click('새 프로젝트로 재사용');await act(async()=>started.promise);await roundtrip();const before=useEditor.getState().project;await act(async()=>job.resolve());await act(async()=>{await repo.list();await new Promise(r=>setTimeout(r,0));});expect(useEditor.getState().project).toBe(before);expect(await repo.list()).toHaveLength(2);expect(reused).not.toHaveBeenCalled();expect(useEditor.getState().message).toBe('다음 작업');});
it('keeps a staged archive copy inactive when new edits arrive before the write acknowledgement',async()=>{await mount(true);await selectArchive();const written=gate<void>(),ack=gate<void>();releases.push(()=>ack.resolve());const save=repo.save.bind(repo);vi.spyOn(repo,'save').mockImplementationOnce(async(...args)=>{const value=await save(...args);written.resolve();await ack.promise;return value;});await click('새 프로젝트로 재사용');await act(async()=>written.promise);await act(async()=>useEditor.getState().renameProject('재사용 저장 중 새 수정'));await act(async()=>ack.resolve());await waitUi(()=>expect(container.textContent).toContain('작업이 변경'));expect(useEditor.getState().project.name).toBe('재사용 저장 중 새 수정');expect(await repo.list()).toHaveLength(3);expect(await repo.activeId()).toBe(p.id);expect(reused).not.toHaveBeenCalled();});
it('does not activate an archive copy if its deferred open returns after the dialog unmounts',async()=>{await mount(true);await selectArchive();const read=repo.read.bind(repo),entered=gate<void>(),job=gate<Awaited<ReturnType<typeof read>>>();vi.spyOn(repo,'read').mockImplementationOnce(async id=>{const value=await read(id);entered.resolve();await job.promise;return value;});await click('새 프로젝트로 재사용');await act(async()=>entered.promise);await act(async()=>root.unmount());await act(async()=>job.resolve(undefined));await act(async()=>{await repo.list();await new Promise(r=>setTimeout(r,0));});expect(await repo.activeId()).toBe(p.id);expect(useEditor.getState().project).toEqual(p);expect(reused).not.toHaveBeenCalled();});


it('reuses an archived exhibition through the parent project dialog and closes the parent once',async()=>{await repo.archive(old.id,true,1);await mount();await click('전시 아카이브');await waitUi(()=>expect(container.querySelector('dialog[aria-label="전시 아카이브"]')).not.toBeNull());await selectArchive();await click('새 프로젝트로 재사용');await waitUi(()=>expect(useEditor.getState().project.name).toBe('지난 전시 재사용'));expect(close).toHaveBeenCalledTimes(1);expect((await repo.read(old.id))?.summary.archived).toBe(true);expect(await readDraft()).toEqual(useEditor.getState().project);});
it('preserves unsaved current edits as a new copy after the original autosave fails',async()=>{writer.mockImplementationOnce(async()=>{throw new Error('기존 프로젝트 저장 실패');});await act(async()=>useEditor.getState().renameProject('저장되지 않은 최신 작업'));await mount();expect(container.textContent).toContain('기존 프로젝트 저장 실패');await click('현재 작업 복사본 만들기');await waitUi(()=>expect(useEditor.getState().project.name).toBe('저장되지 않은 최신 작업 복사본'));const next=useEditor.getState().project;expect({...next,id:p.id,name:p.name}).toEqual(p);expect((await repo.read(p.id))?.project).toEqual(p);expect(await readDraft()).toEqual(next);expect(close).toHaveBeenCalledTimes(1);});
it('rejects a stale project archive card after another repository saves a new revision',async()=>{await mount();await libraries.createProjectLibrary(factory,dbName).save({...old,name:'다른 탭 최신 전시'},1);await click('지난 전시 보관');await waitUi(()=>expect(container.textContent).toContain('다른 탭'));expect((await repo.read(old.id))?.summary).toMatchObject({name:'다른 탭 최신 전시',archived:false,revision:2});expect(useEditor.getState().project).toEqual(p);expect(close).not.toHaveBeenCalled();});
it('aborts activation if an edit arrives during the actual IndexedDB summary query',async()=>{await mount();const get=IDBObjectStore.prototype.get;vi.spyOn(IDBObjectStore.prototype,'get').mockImplementation(function(this:IDBObjectStore,key){const request=get.call(this,key);if(this.name==='summaries'&&this.transaction.mode==='readwrite'&&key===old.id)request.addEventListener('success',()=>useEditor.getState().renameProject('활성화 중 새 수정'),{once:true});return request;});await click('열기',card());await waitUi(()=>expect(container.textContent).toContain('작업이 변경'));expect(useEditor.getState().project.name).toBe('활성화 중 새 수정');expect(await repo.activeId()).toBe(p.id);expect(localProjectRevision(old.id)).toBeUndefined();expect(close).not.toHaveBeenCalled();});
