// @vitest-environment jsdom
import {act,StrictMode} from 'react';
import {createRoot,type Root} from 'react-dom/client';
import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {Blob as NodeBlob} from 'node:buffer';
import {IDBFactory,IDBObjectStore} from 'fake-indexeddb';
import {createCanvas,loadImage} from '@napi-rs/canvas';
import ProjectHistoryDialog from './ProjectHistoryDialog';
import {ProjectsDialog} from './ProjectsDialog';
vi.mock('./CloudProjectsPanel',()=>({CloudProjectsPanel:()=>null}));
import {useEditor,startAutosave,captureAutosaveFlush} from '../state/editor';
import {createDemoProject,parseProject} from '../domain/model';
import {appendSceneSnapshot} from '../domain/sceneSnapshot';
import {materialPreset} from '../domain/materials';
import type {Project} from '../domain/types';
import * as projects from '../lib/projectLibrary';
import * as history from '../lib/projectHistory';
import {saveNewLocalProject,writeDraft,readDraft,localProjectRevision} from '../lib/persistence';
import {exportProjectBackup,verifyProjectBackupImages} from '../lib/projectBackup';
import {importProjectPackage,exportProjectPackage} from '../lib/projectPackage';
import {testVenueModel} from '../lib/venueModelTestFixture';
import {downloadBlob} from '../lib/art';
vi.mock('../lib/projectBackup',async original=>{const actual=await original<typeof import('../lib/projectBackup')>();return {...actual,exportProjectBackup:vi.fn(actual.exportProjectBackup),verifyProjectBackupImages:vi.fn(actual.verifyProjectBackupImages)};});
vi.mock('../lib/art',async original=>({...await original<typeof import('../lib/art')>(),downloadBlob:vi.fn()}));
// Only preview transport is replaced. Actual native image/ZIP/DB work runs below.
vi.mock('./PresentationMode',()=>({default:({source}:{source:{project:Project}})=><div aria-label="미리보기 프로젝트">{source.project.name}</div>}));
vi.setConfig({testTimeout:10000});
let root:Root,container:HTMLDivElement,p:Project,original:Project,repo:ReturnType<typeof projects.createProjectLibrary>,h:ReturnType<typeof history.createProjectHistory>,factory:IDBFactory,hName:string,dbName:string,point:Awaited<ReturnType<typeof h.add>>,stop:()=>void,imageUrl:string;
const close=vi.fn(),restored=vi.fn();let releases:Array<()=>void>=[],pending=new Set<Promise<unknown>>();
function track<T>(promise:Promise<T>){pending.add(promise);void promise.then(()=>pending.delete(promise),()=>pending.delete(promise));return promise;}
async function drain(){const deadline=Date.now()+5000;for(;;){await act(async()=>{await Promise.allSettled([...pending]);await Promise.all([repo.list(),h.list(p.id)]);await new Promise(r=>setTimeout(r,0));});if(!pending.size)return;if(Date.now()>deadline)throw new Error('Pending production work did not settle');}}
function deferred<T>(){let resolve!:(value:T)=>void;const promise=new Promise<T>(r=>resolve=r);return {promise,resolve};}
async function tick(){await act(async()=>{await Promise.all([repo.list(),h.list(p.id)]);await new Promise(r=>setTimeout(r,0));});}
async function waitUi(assertion:()=>void){const deadline=Date.now()+5000;for(;;){await tick();try{assertion();return;}catch(error){if(Date.now()>=deadline)throw error;}}}
async function render(projectId=p.id){await act(async()=>root.render(<StrictMode><ProjectHistoryDialog projectId={projectId} onClose={close} onRestored={restored}/></StrictMode>));}
async function mount(){await render();await waitUi(()=>{expect(container.querySelector('.history-select')).not.toBeNull();expect(container.textContent).not.toContain('버전 처리 중');});}
async function click(label:string){let button!:HTMLButtonElement;await waitUi(()=>{button=[...container.querySelectorAll<HTMLButtonElement>('button')].find(b=>b.getAttribute('aria-label')===label||b.textContent?.trim()===label)!;expect(button,container.textContent).toBeDefined();expect(button.matches(':disabled'),container.textContent).toBe(false);});await act(async()=>button.click());}
async function input(value:string){const field=container.querySelector<HTMLInputElement>('[aria-label="복원 지점 이름"]')!;await act(async()=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')!.set!.call(field,value);field.dispatchEvent(new Event('input',{bubbles:true}));});}
async function select(){await click('설치 전 버전 비교');await waitUi(()=>expect(container.querySelector('.history-comparison')).not.toBeNull());}
async function check(){const checkbox=container.querySelector<HTMLInputElement>('.history-tools input')!;await act(async()=>checkbox.click());}
async function roundtrip(){await act(async()=>{useEditor.getState().loadProject({...p,id:'other-history-project'});useEditor.getState().loadProject(p);useEditor.getState().notify('다음 편집 알림');});}
beforeEach(async()=>{
 vi.resetAllMocks();releases=[];pending=new Set();(globalThis as typeof globalThis&{IS_REACT_ACT_ENVIRONMENT:boolean}).IS_REACT_ACT_ENVIRONMENT=true;vi.stubGlobal('Blob',NodeBlob);Object.defineProperty(HTMLDialogElement.prototype,'showModal',{configurable:true,value:function(this:HTMLDialogElement){this.open=true;}});
 class NativeImage {naturalWidth=0;naturalHeight=0;onload:(()=>void)|null=null;onerror:(()=>void)|null=null;set src(value:string){if(!value)return;void track(loadImage(value)).then(image=>{this.naturalWidth=image.width;this.naturalHeight=image.height;this.onload?.();},()=>this.onerror?.());}}vi.stubGlobal('Image',NativeImage);
 const canvas=createCanvas(32,16),ctx=canvas.getContext('2d');ctx.fillStyle='#80c8ff';ctx.fillRect(0,0,32,16);imageUrl=canvas.toDataURL('image/png');factory=new IDBFactory();dbName='history-projects-ui-'+crypto.randomUUID();hName='history-points-ui-'+crypto.randomUUID();repo=projects.createProjectLibrary(factory,dbName);h=history.createProjectHistory(factory,hName);vi.spyOn(projects,'projectLibrary').mockReturnValue(repo);vi.spyOn(history,'projectHistory').mockReturnValue(h);
 original={...createDemoProject(),id:crypto.randomUUID(),name:'버전 전시',displayUnit:'cm',note:'PRIVATE_OLD',scenes:[],referenceModel:{...testVenueModel(),note:'PRIVATE_MODEL'},noteDetails:{checklist:[{id:'print',text:'출력 완료',done:true}],images:[{id:'photo',name:'현장.png',imageUrl}]}};original.artworks=original.artworks.slice(0,1).map(a=>({...a,imageUrl,note:'PRIVATE_ART'}));original.walls[0].material={...materialPreset('wood').material,normal:{imageUrl,widthMm:500,heightMm:250,strength:1.5}};original=appendSceneSnapshot(original,original,'설치 Scene');
 const actual=await vi.importActual<typeof import('../lib/projectBackup')>('../lib/projectBackup');vi.mocked(exportProjectBackup).mockImplementation((...args)=>track(actual.exportProjectBackup(...args)));vi.mocked(verifyProjectBackupImages).mockImplementation((...args)=>track(actual.verifyProjectBackupImages(...args)));
 const read=repo.read.bind(repo),save=repo.save.bind(repo),readVersion=h.read.bind(h),add=h.add.bind(h);vi.spyOn(repo,'read').mockImplementation((...args)=>track(read(...args)));vi.spyOn(repo,'save').mockImplementation((...args)=>track(save(...args)));vi.spyOn(h,'read').mockImplementation((...args)=>track(readVersion(...args)));vi.spyOn(h,'add').mockImplementation((...args)=>track(add(...args)));
 await saveNewLocalProject(original);point=await h.add(original.id,'설치 전',1,await exportProjectBackup(original));p=parseProject({...original,name:'최신 전시',note:'PRIVATE_CURRENT',artworks:original.artworks.map(a=>({...a,widthMm:1100}))});await writeDraft(p);useEditor.getState().loadProject(p,true);stop=startAutosave(writeDraft,60000);container=document.createElement('div');document.body.append(container);root=createRoot(container);vi.mocked(exportProjectBackup).mockClear();vi.mocked(verifyProjectBackupImages).mockClear();
});
afterEach(async()=>{for(const release of releases)release();await act(async()=>root.unmount());container.remove();const finish=captureAutosaveFlush();stop();await finish().catch(()=>{});await drain();vi.restoreAllMocks();vi.unstubAllGlobals();});

it('saves and compares real media ZIPs, restores with a durable rescue version and permits the next autosave',async()=>{
 await mount();await input('현재 설치');await click('현재 버전 저장');await waitUi(()=>expect(container.textContent).toContain('현재 설치'));const currentPoint=(await h.list(p.id)).find(x=>x.label==='현재 설치')!;expect((await history.createProjectHistory(factory,hName).read(p.id,currentPoint.id)).project).toEqual(p);expect(currentPoint.sourceRevision).toBe(2);await select();expect(container.querySelector('.history-comparison')?.textContent).toContain('작품');expect(container.querySelector('.history-comparison')?.textContent).toContain('프로젝트 메모');expect(useEditor.getState().project).toEqual(p);await click('이 버전으로 복원');await waitUi(()=>expect(restored).toHaveBeenCalledTimes(1));expect(useEditor.getState().project).toEqual(original);expect(useEditor.getState().past).toHaveLength(0);expect(await readDraft()).toEqual(original);expect(localProjectRevision(p.id)).toBe(3);const rescue=(await h.list(p.id)).find(x=>x.label.startsWith('복원 전'))!;expect((await h.read(p.id,rescue.id)).project).toEqual(p);await act(async()=>useEditor.getState().patchArtwork(original.artworks[0].id,{widthMm:950}));await act(async()=>captureAutosaveFlush()());expect((await repo.read(p.id))?.project.artworks[0].widthMm).toBe(950);expect(localProjectRevision(p.id)).toBe(4);expect(container.querySelector('[role="alert"]')).toBeNull();
});
it('backs up exact version bytes and confirms deletion only for an archived record',async()=>{await mount();const before=useEditor.getState().project;await click('설치 전 버전 백업');await waitUi(()=>expect(downloadBlob).toHaveBeenCalledTimes(1));const [blob,name]=vi.mocked(downloadBlob).mock.calls[0];expect(name).toBe('버전 전시-설치 전.gonggan.zip');expect(await importProjectPackage(await blob.arrayBuffer())).toEqual(original);await click('설치 전 버전 보관');await waitUi(()=>expect(container.querySelector('.history-card')).toBeNull());await check();await click('설치 전 버전 복구');await waitUi(()=>expect(container.querySelector('.history-card')).toBeNull());await check();await click('설치 전 버전 보관');await waitUi(()=>expect(container.querySelector('.history-card')).toBeNull());await check();await click('설치 전 버전 삭제');expect(container.querySelector('[role="alertdialog"]')).not.toBeNull();expect(await h.list(p.id)).toHaveLength(1);await click('취소');expect(await h.list(p.id)).toHaveLength(1);await click('설치 전 버전 삭제');await click('버전 영구 삭제');await waitUi(()=>expect(container.querySelector('.history-card')).toBeNull());expect(await h.usage()).toBe(0);expect(useEditor.getState().project).toBe(before);expect((await repo.read(p.id))?.project).toEqual(p);});
it.each(['unmount','roundtrip'] as const)('starts no version write when backup preparation finishes after %s',async transition=>{await mount();const job=deferred<Blob>(),blob=await exportProjectBackup(p);vi.mocked(exportProjectBackup).mockImplementationOnce(()=>job.promise);await input('늦은 버전');await click('현재 버전 저장');await waitUi(()=>expect(exportProjectBackup).toHaveBeenCalledTimes(2));if(transition==='unmount')await act(async()=>root.unmount());else await roundtrip();await act(async()=>job.resolve(blob));await drain();expect(await h.list(p.id)).toHaveLength(1);expect(useEditor.getState().project.id).toBe(p.id);});
it('does not download a pending version backup after unmount',async()=>{await mount();const blob=await h.backup(p.id,point.id),job=deferred<Blob>();vi.spyOn(h,'backup').mockImplementationOnce(()=>job.promise);await click('설치 전 버전 백업');await act(async()=>root.unmount());await act(async()=>job.resolve(blob));expect(downloadBlob).not.toHaveBeenCalled();});
it.each(['unmount','roundtrip'] as const)('does not decode or compare a version read after %s',async transition=>{await mount();const value=await h.read(p.id,point.id),job=deferred<typeof value>();vi.spyOn(h,'read').mockImplementationOnce(()=>job.promise);await click('설치 전 버전 비교');if(transition==='unmount')await act(async()=>root.unmount());else await roundtrip();await act(async()=>job.resolve(value));await drain();expect(verifyProjectBackupImages).not.toHaveBeenCalled();expect(exportProjectBackup).not.toHaveBeenCalled();expect(container.querySelector('.history-comparison')).toBeNull();});
it.each(['unmount','roundtrip'] as const)('does not replace the document when restore read finishes after %s',async transition=>{await mount();await select();const value=await h.read(p.id,point.id),job=deferred<typeof value>();vi.spyOn(h,'read').mockImplementationOnce(()=>job.promise);await click('이 버전으로 복원');await waitUi(()=>expect(h.read).toHaveBeenCalledTimes(3));if(transition==='unmount')await act(async()=>root.unmount());else await roundtrip();const before=useEditor.getState().project;await act(async()=>job.resolve(value));await drain();expect(useEditor.getState().project).toBe(before);expect((await repo.read(p.id))?.project).toEqual(p);expect(await h.list(p.id)).toHaveLength(1);expect(restored).not.toHaveBeenCalled();});
it('preserves edits arriving during rescue backup and allows a fresh comparison',async()=>{await mount();await select();const blob=await exportProjectBackup(p),job=deferred<Blob>();vi.mocked(exportProjectBackup).mockImplementationOnce(()=>job.promise);await click('이 버전으로 복원');await waitUi(()=>expect(exportProjectBackup).toHaveBeenCalledTimes(3));await act(async()=>useEditor.getState().renameProject('복원 중 새 수정'));await act(async()=>job.resolve(blob));await waitUi(()=>expect(container.textContent).toContain('작업이 변경'));expect(useEditor.getState().project.name).toBe('복원 중 새 수정');expect(await h.list(p.id)).toHaveLength(1);expect(restored).not.toHaveBeenCalled();expect(container.querySelector('.history-comparison')).toBeNull();await waitUi(()=>expect(container.textContent).not.toContain('버전 처리 중'));await select();expect(container.querySelector('.history-comparison')?.textContent).toContain('프로젝트 이름');});
it('does not show an old comparison after a subsequent edit and rejects restoration during a gesture',async()=>{await mount();await select();await act(async()=>useEditor.getState().renameProject('비교 후 새 수정'));expect(container.querySelector('.history-comparison')).toBeNull();await select();await act(async()=>useEditor.setState({previewProject:useEditor.getState().project}));await click('이 버전으로 복원');await waitUi(()=>expect(container.textContent).toContain('이동·회전'));expect(useEditor.getState().project.name).toBe('비교 후 새 수정');expect(await h.list(p.id)).toHaveLength(1);expect(restored).not.toHaveBeenCalled();});
it('resets version data on target change and discards the previous pending result',async()=>{await mount();const value=await h.read(p.id,point.id),job=deferred<typeof value>();vi.spyOn(h,'read').mockImplementationOnce(()=>job.promise);await click('설치 전 버전 비교');const other=parseProject({...p,id:crypto.randomUUID(),name:'다른 버전 대상'});await repo.save(other,0,false);await render(other.id);await waitUi(()=>expect(container.textContent).toContain(other.name));await act(async()=>job.resolve(value));await drain();expect(container.querySelector('.history-comparison')).toBeNull();expect(container.textContent).not.toContain('설치 전');expect(useEditor.getState().project.id).toBe(p.id);});
it('preserves current work when the safety-point limit prevents restore',async()=>{h=history.createProjectHistory(factory,hName,{bytes:200*1024*1024,points:1});vi.mocked(history.projectHistory).mockReturnValue(h);await mount();await select();await click('이 버전으로 복원');await waitUi(()=>expect(container.textContent).toContain('버전은 1개'));expect(useEditor.getState().project).toEqual(p);expect((await repo.read(p.id))?.project).toEqual(p);expect(await h.list(p.id)).toHaveLength(1);expect(restored).not.toHaveBeenCalled();});
it('rejects another repository revision during restore without overwriting it',async()=>{await mount();await select();const other={...p,note:'OTHER_TAB'};await projects.createProjectLibrary(factory,dbName).save(other,2,false);await click('이 버전으로 복원');await waitUi(()=>expect(container.textContent).toContain('다른 탭'));expect(useEditor.getState().project).toEqual(p);expect((await repo.read(p.id))?.project).toEqual(other);expect(await h.list(p.id)).toHaveLength(1);expect(restored).not.toHaveBeenCalled();});
it('aborts the actual replacement transaction when new editing occurs in its summary query',async()=>{await mount();await select();const get=IDBObjectStore.prototype.get;vi.spyOn(IDBObjectStore.prototype,'get').mockImplementation(function(this:IDBObjectStore,key){const request=get.call(this,key);if(this.name==='summaries'&&this.transaction.mode==='readwrite'&&key===p.id)request.addEventListener('success',()=>useEditor.getState().renameProject('저장 직전 추가 편집'),{once:true});return request;});await click('이 버전으로 복원');await waitUi(()=>expect(container.textContent).toContain('작업이 변경'));expect(useEditor.getState().project.name).toBe('저장 직전 추가 편집');expect((await repo.read(p.id))?.project).toEqual(p);expect((await h.list(p.id)).some(i=>i.label.startsWith('복원 전'))).toBe(true);expect(restored).not.toHaveBeenCalled();expect(localProjectRevision(p.id)).toBe(2);});
it('rejects damaged native image assets in a checksum-valid version before restoration',async()=>{const broken='data:image/png;base64,'+Buffer.from(imageUrl.split(',')[1],'base64').subarray(0,30).toString('base64'),bad={...original,artworks:original.artworks.map(a=>({...a,imageUrl:broken}))};await h.add(p.id,'손상 자산',1,await exportProjectPackage(bad,async()=>imageUrl));await mount();await click('손상 자산 버전 비교');await waitUi(()=>expect(container.textContent).toContain('이미지를 읽지 못'));expect(container.querySelector('.history-comparison')).toBeNull();expect(useEditor.getState().project).toEqual(p);expect(restored).not.toHaveBeenCalled();});

it('retains an accepted rescue point without replacing the editor after a new edit',async()=>{await mount();await select();const add=h.add.bind(h),written=deferred<void>(),ack=deferred<void>();releases.push(()=>ack.resolve());vi.spyOn(h,'add').mockImplementationOnce(async(...args)=>{const value=await add(...args);written.resolve();await ack.promise;return value;});await click('이 버전으로 복원');await act(async()=>written.promise);await act(async()=>useEditor.getState().renameProject('안전 보관 중 새 수정'));await act(async()=>ack.resolve());await drain();expect(useEditor.getState().project.name).toBe('안전 보관 중 새 수정');expect((await repo.read(p.id))?.project).toEqual(p);expect(await h.list(p.id)).toHaveLength(2);expect(container.textContent).toContain('복원 전 자동 보관');expect(restored).not.toHaveBeenCalled();expect(localProjectRevision(p.id)).toBe(2);});
it('acknowledges an accepted replacement without discarding later edits or breaking the next autosave',async()=>{await mount();await select();const save=repo.save.bind(repo),written=deferred<void>(),ack=deferred<void>();releases.push(()=>ack.resolve());vi.spyOn(repo,'save').mockImplementationOnce(async(...args)=>{const value=await save(...args);written.resolve();await ack.promise;return value;});await click('이 버전으로 복원');await act(async()=>written.promise);expect((await repo.read(p.id))?.project).toEqual(original);await act(async()=>useEditor.getState().renameProject('저장 수락 후 추가 편집'));await act(async()=>ack.resolve());await drain();expect(useEditor.getState().project.name).toBe('저장 수락 후 추가 편집');expect(restored).not.toHaveBeenCalled();expect(localProjectRevision(p.id)).toBe(3);await act(async()=>captureAutosaveFlush()());expect((await repo.read(p.id))?.project).toEqual({...p,name:'저장 수락 후 추가 편집'});expect(localProjectRevision(p.id)).toBe(4);expect(useEditor.getState().saveStatus).toBe('saved');expect(await h.list(p.id)).toHaveLength(2);});

it('restores another project through the parent project list and closes it once',async()=>{const otherOriginal=parseProject({...original,id:crypto.randomUUID(),name:'다른 기록'});await repo.save(otherOriginal,0,false);await h.add(otherOriginal.id,'다른 설치 전',1,await exportProjectBackup(otherOriginal));const otherCurrent=parseProject({...otherOriginal,artworks:otherOriginal.artworks.map(a=>({...a,widthMm:1500}))});await repo.save(otherCurrent,1,false);await act(async()=>root.render(<StrictMode><ProjectsDialog onClose={close}/></StrictMode>));await click('다른 기록 버전 기록');await click('다른 설치 전 버전 비교');await waitUi(()=>expect(container.querySelector('.history-comparison')).not.toBeNull());await click('이 버전으로 복원');await waitUi(()=>expect(useEditor.getState().project.id).toBe(otherOriginal.id));expect(useEditor.getState().project).toEqual(otherOriginal);expect(await readDraft()).toEqual(otherOriginal);expect(close).toHaveBeenCalledTimes(1);expect((await repo.read(p.id))?.project).toEqual(p);});
