import {useEffect,useMemo,useRef,useState} from 'react';
import {cloudSession,initializeAuth,useAuth} from '../state/auth';
import {createReviewClient,ReviewClientError,type ReviewDraft} from '../lib/reviewClient';
import {resolveReviewAnchor,REVIEW_TEXT_MAX,REVIEW_POSTS_MAX,type ReviewAnchor,type ReviewMutation,type ReviewPage,type ReviewThread} from '../domain/reviewComments';
import type {PublicShareSnapshot} from '../domain/publicShare';
import {formatLength} from '../domain/lengthUnits';
import {AccountDialog} from './AccountDialog';
import {NumberField} from './Controls';
import './reviewComments.css';
type Selection={kind:'wall'|'artwork'|'modelArtwork'|'referenceModel';id:string}|null;
type Tagged<T>={context:string;value:T};
export function ReviewThreadCard({thread,owner,canComment,busy,onChange,onAnchor}:{thread:ReviewThread;owner:boolean;canComment:boolean;busy:boolean;onChange:(id:string,revision:number,change:ReviewMutation)=>Promise<boolean>;onAnchor?:(anchor:ReviewAnchor)=>void}){
 const [reply,setReply]=useState(''),[replyId,setReplyId]=useState(()=>crypto.randomUUID()),[name,setName]=useState('참여자'),[edit,setEdit]=useState<{id:string;text:string;revision:number}|null>(null);
 return <article className="review-thread" aria-label={`${thread.anchor.label} 의견`}><header><span><strong>{thread.anchor.sceneName} · {thread.anchor.label}</strong><small>{thread.resolved?'처리 완료':'열린 의견'} · {new Date(thread.createdAt).toLocaleString('ko-KR')}</small></span>{onAnchor&&<button type="button" className="button secondary" onClick={()=>onAnchor(thread.anchor)}>대상 보기</button>}</header>
 {thread.posts.map(p=><section key={p.id} className="review-post"><div><strong>{p.deleted?'삭제된 댓글':p.name}{p.mine&&!p.deleted?' · 나':''}</strong><small>{new Date(p.createdAt).toLocaleString('ko-KR')}{p.editedAt?' · 수정됨':''}</small></div>{p.deleted?<p className="field-hint">삭제된 댓글입니다.</p>:edit?.id===p.id?<form onSubmit={async e=>{e.preventDefault();if(await onChange(thread.id,edit.revision,{action:'edit',id:p.id,text:edit.text}))setEdit(null);}}><label>댓글 수정<textarea required maxLength={REVIEW_TEXT_MAX} disabled={busy} value={edit.text} onChange={e=>setEdit({...edit,text:e.target.value})}/></label><button className="button secondary" disabled={busy||!edit.text.trim()}>수정 저장</button><button type="button" className="button secondary" disabled={busy} onClick={()=>setEdit(null)}>취소</button></form>:<p className="review-text">{p.text}</p>}{!p.deleted&&canComment&&<div className="review-post-actions">{p.mine&&<button type="button" disabled={busy} onClick={()=>setEdit({id:p.id,text:p.text,revision:thread.revision})}>수정</button>}{(p.mine||owner)&&<button type="button" disabled={busy} onClick={()=>void onChange(thread.id,thread.revision,{action:'deletePost',id:p.id})}>댓글 삭제</button>}</div>}</section>)}
 {canComment&&thread.canManage&&<div className="review-actions"><button type="button" className="button secondary" disabled={busy} onClick={()=>void onChange(thread.id,thread.revision,{action:'resolve',resolved:!thread.resolved})}>{thread.resolved?'다시 열기':'처리 완료'}</button><button type="button" className="button secondary" disabled={busy} onClick={()=>void onChange(thread.id,thread.revision,{action:'deleteThread'})}>의견 전체 삭제</button></div>}
 {canComment&&!thread.resolved&&thread.posts.length<REVIEW_POSTS_MAX&&<form className="review-reply" onSubmit={async e=>{e.preventDefault();if(await onChange(thread.id,thread.revision,{action:'reply',id:replyId,name,text:reply})){setReply('');setReplyId(crypto.randomUUID());}}}><label>답글 표시 이름<input required maxLength={80} disabled={busy} value={name} onChange={e=>{setName(e.target.value);setReplyId(crypto.randomUUID());}}/></label><label>답글<textarea required maxLength={REVIEW_TEXT_MAX} disabled={busy} value={reply} onChange={e=>{setReply(e.target.value);setReplyId(crypto.randomUUID());}}/></label><button className="button secondary" disabled={busy||!reply.trim()||!name.trim()}>답글 등록</button></form>}
 </article>;
}
/** Public opinions only. Has no Project/Note persistence or editor action dependency. */
export function ReviewCommentsPanel({shareId,publication,sceneId=null,selection=null,onAnchor,credential,credentialIdentity,privateProject}:{shareId:string;publication?:PublicShareSnapshot;privateProject?:{id:string;name:string};sceneId?:string|null;selection?:Selection;onAnchor?:(anchor:ReviewAnchor)=>void;credential?:()=>Promise<string>;credentialIdentity?:string}){
 // Scope and actor are both part of the cache/request identity; credentials stay out of it.
 const auth=useAuth(),context=JSON.stringify([privateProject?'private':'public',shareId,credential?'owner':'account',credential?credentialIdentity??auth.user?.id??'legacy':auth.user?.id??null]);
 const live=useRef(context);live.current=context;const mounted=useRef(false),controller=useRef<AbortController|null>(null),epoch=useRef(0),working=useRef(false);
 const [data,setData]=useState<Tagged<ReviewPage>>(),[pending,setPending]=useState<Tagged<boolean>>(),[error,setError]=useState<Tagged<string>>(),[account,setAccount]=useState(false),[filter,setFilter]=useState<'all'|'open'|'resolved'>('all');
 const [name,setName]=useState('참여자'),[text,setText]=useState(''),[ids,setIds]=useState(()=>({id:crypto.randomUUID(),postId:crypto.randomUUID()})),[mode,setMode]=useState<'selection'|'project'|'point'>('selection'),[point,setPoint]=useState({x:0,y:1500,z:0});
 const page=data?.context===context?data.value:undefined,busy=pending?.context===context&&pending.value;
 const anchor=useMemo(()=>privateProject?{kind:'project' as const,sceneId:null,label:privateProject.name,sceneName:'공동 프로젝트'}:resolveReviewAnchor(publication!,{sceneId,kind:mode==='point'?'point':mode==='selection'&&selection?selection.kind:'project',...(mode==='point'?{point}:mode==='selection'&&selection?{id:selection.id}:{})}),[publication,privateProject,sceneId,selection,mode,point]);
 useEffect(()=>{mounted.current=true;if(!credential)void initializeAuth();return()=>{mounted.current=false;epoch.current++;controller.current?.abort();};},[]); // Credentials come from the owning Share dialog, never URL storage.
 useEffect(()=>{controller.current?.abort();working.current=false;setData(undefined);setError(undefined);setText('');setName('참여자');setFilter('all');setMode('selection');setPoint({x:0,y:1500,z:0});setAccount(false);setIds({id:crypto.randomUUID(),postId:crypto.randomUUID()});void refresh();return()=>{controller.current?.abort();};},[context]); // eslint-disable-line react-hooks/exhaustive-deps
 useEffect(()=>{setIds({id:crypto.randomUUID(),postId:crypto.randomUUID()});},[anchor]);
 useEffect(()=>{const timer=window.setInterval(()=>{if(document.visibilityState==='visible'&&!working.current)void refresh();},30000);return()=>window.clearInterval(timer);},[context]); // eslint-disable-line react-hooks/exhaustive-deps
 function begin(){working.current=true;controller.current?.abort();const c=new AbortController(),operation=++epoch.current,captured=context;controller.current=c;setPending({context:captured,value:true});setError(undefined);
  const guard=()=>{if(!mounted.current||c.signal.aborted||live.current!==captured||epoch.current!==operation||!credential&&useAuth.getState().user?.id!==auth.user?.id)throw new Error('계정이 바뀌어 댓글 작업을 취소했습니다.');};return {c,captured,guard};
 }
 async function client(guard:()=>void,c:AbortController){let token:string|undefined;if(credential){token=await credential();guard();}else if(auth.user){const session=await cloudSession();guard();if(session.userId!==auth.user.id)throw new Error('로그인 계정이 바뀌었습니다.');token=session.token;}return createReviewClient(shareId,token,fetch,c.signal,privateProject?'project':'public');}
 function fail(e:unknown,c:AbortController,captured:string){if(mounted.current&&!c.signal.aborted&&live.current===captured){if(e instanceof ReviewClientError&&(e.status===404||e.status===410))setData(undefined);setError({context:captured,value:e instanceof ReviewClientError&&e.status===409?e.message+' 입력은 유지됩니다.':e instanceof Error?e.message:'댓글을 저장하지 못했습니다. 입력은 유지됩니다.'});}}
 function finish(c:AbortController,captured:string){if(mounted.current&&controller.current===c){working.current=false;setPending({context:captured,value:false});}}
 async function refresh(before?:string){if(working.current)return;const {c,captured,guard}=begin();try{const result=await(await client(guard,c)).list(before);guard();setData(old=>({context:captured,value:{...result,items:before&&old?.context===captured?[...old.value.items,...result.items].filter((t,i,all)=>all.findIndex(v=>v.id===t.id)===i):result.items}}));}catch(e){fail(e,c,captured);}finally{finish(c,captured);}}
 async function create(){if(working.current||!page?.canComment)return;const {c,captured,guard}=begin(),draft:ReviewDraft={...ids,name,text,anchor};try{const result=await(await client(guard,c)).create(draft);guard();setData(old=>({context:captured,value:{...result,nextCursor:old?.context===captured?old.value.nextCursor:null,items:[...result.items,...(old?.context===captured?old.value.items:[])].filter((t,i,all)=>all.findIndex(v=>v.id===t.id)===i)}}));setText('');setIds({id:crypto.randomUUID(),postId:crypto.randomUUID()});}catch(e){fail(e,c,captured);}finally{finish(c,captured);}}
 async function change(id:string,revision:number,action:ReviewMutation){if(working.current||!page?.canComment)return false;const {c,captured,guard}=begin();try{const result=await(await client(guard,c)).change(id,revision,action);guard();setData(old=>old?.context===captured?{context:captured,value:{...old.value,items:result?old.value.items.map(t=>t.id===id?result.items[0]:t):old.value.items.filter(t=>t.id!==id)}}:old);return true;}catch(e){fail(e,c,captured);return false;}finally{finish(c,captured);}}
 return <section className="review-panel" aria-label="협업 댓글"><header><h2>협업 댓글</h2><button type="button" className="button secondary" disabled={busy} onClick={()=>void refresh()}>새로고침</button></header><p className="field-hint">{privateProject?'참여자만 읽는 공동 프로젝트 의견입니다. 내부 설치 메모와 별도 저장합니다. 열람자는 작성할 수 없습니다.':'링크를 가진 사람이 읽는 외부 의견입니다. 배치는 잠겨 있으며 내부 설치 메모와 별도 저장합니다.'}</p>
 {!page?.canComment&&!credential&&!auth.user&&<p className="field-hint">{auth.status==='loading'?'댓글 로그인 연결 확인 중…':auth.status==='disabled'?'댓글은 읽을 수 있습니다. 계정 연결이 준비되면 작성할 수 있습니다.':'댓글을 작성하려면 계정에 로그인하세요.'}{auth.status!=='disabled'&&auth.status!=='loading'&&<button type="button" className="button secondary" onClick={()=>setAccount(true)}>댓글 계정 로그인</button>}</p>}
 {error?.context===context&&<p className="warning" role="alert">{error.value}</p>}{busy&&<p role="status">댓글 처리 중…</p>}{page&&!page.enabled&&<p>댓글을 허용하지 않은 링크입니다.</p>}
 {page?.canComment&&<form className="review-compose" onSubmit={e=>{e.preventDefault();void create();}}>{!privateProject&&<label>의견 대상<select disabled={busy} value={mode} onChange={e=>setMode(e.target.value as typeof mode)}><option value="selection">{selection?'선택한 벽·작품':'전시 전체'}</option><option value="project">전시 전체</option><option value="point">공간 위치</option></select></label>}<p>{anchor.sceneName} · {anchor.label}</p>{!privateProject&&mode==='point'&&(['x','y','z'] as const).map(k=><NumberField key={k} label={`댓글 위치 ${k.toUpperCase()}`} value={point[k]} min={-1e7} max={1e7} disabled={busy} onChange={value=>setPoint({...point,[k]:value})}/>)}<label>표시 이름<input required maxLength={80} disabled={busy} value={name} onChange={e=>{setName(e.target.value);setIds({id:crypto.randomUUID(),postId:crypto.randomUUID()});}}/></label><p className="field-hint">직접 입력한 표시 이름이며 계정 이메일은 공개하지 않습니다.</p><label>협업 의견<textarea required maxLength={REVIEW_TEXT_MAX} disabled={busy} value={text} onChange={e=>{setText(e.target.value);setIds({id:crypto.randomUUID(),postId:crypto.randomUUID()});}}/></label><button className="button primary" disabled={busy||!text.trim()||!name.trim()}>의견 등록</button></form>}
 {page?.enabled&&<><label className="review-filter">의견 상태<select value={filter} onChange={e=>setFilter(e.target.value as typeof filter)}><option value="all">전체</option><option value="open">열린 의견</option><option value="resolved">처리 완료</option></select></label><div className="review-threads">{page.items.filter(t=>filter==='all'||t.resolved===(filter==='resolved')).map(t=><div key={t.id}>{t.anchor.point&&<p className="field-hint">X {formatLength(t.anchor.point.x,publication?.displayUnit??'mm')} · Y {formatLength(t.anchor.point.y,publication?.displayUnit??'mm')} · Z {formatLength(t.anchor.point.z,publication?.displayUnit??'mm')}</p>}<ReviewThreadCard thread={t} owner={page.owner} canComment={page.canComment} busy={!!busy} onChange={change} onAnchor={onAnchor}/></div>)}{!page.items.length&&!busy&&<p>아직 의견이 없습니다.</p>}</div>{page.nextCursor&&<button type="button" className="button secondary" disabled={busy} onClick={()=>void refresh(page.nextCursor!)}>이전 의견 더 보기</button>}</>}
 {account&&<AccountDialog returnPath={'/s/'+shareId} onClose={()=>setAccount(false)}/>}
 </section>;
}
