import {useEffect,useState,useSyncExternalStore,useRef} from 'react';
import {videoPlayback,videoSessionKey,type VideoSession,type VideoStatus} from '../lib/videoPlayback';
import {useEditor} from '../state/editor';
import type {Artwork} from '../domain/types';
const idle:VideoStatus={playing:false,ready:false,timeSeconds:0,durationSeconds:0,muted:true};
const time=(seconds:number)=>`${Math.floor(seconds/60)}:${String(Math.floor(seconds%60)).padStart(2,'0')}`;
export function VideoArtworkControls({artwork}:{artwork:Artwork}){
 const projectId=useEditor(s=>s.project.id),media=artwork.video!,key=videoSessionKey(projectId,artwork.id),host=useRef<HTMLDivElement>(null);
 const [session,setSession]=useState<VideoSession>(),[error,setError]=useState('');
 useEffect(()=>{let lease:ReturnType<typeof videoPlayback.open>|undefined;setError('');try{lease=videoPlayback.open(key,media);setSession(lease.session);}catch(e){setSession(undefined);setError(e instanceof Error?e.message:'영상 화면을 열지 못했습니다.');}return ()=>lease?.release();},[key,media.dataUrl,media.loop]);
 useEffect(()=>{if(!session||!host.current)return;session.video.poster=artwork.imageUrl;session.video.className='video-preview-native';host.current.appendChild(session.video);return ()=>session.video.remove();},[session,artwork.imageUrl]);
 const status=useSyncExternalStore(f=>session?.subscribe(f)??(()=>{}),()=>session?.snapshot??idle);
 const patch=(video:Artwork['video'])=>useEditor.getState().patchArtwork(artwork.id,{video});
 return <section className="inspector-section video-artwork-controls" aria-label="영상 작품"><h3>영상 · 스크린</h3><div ref={host}/><div className="rotation-buttons"><button className="button secondary" disabled={!session||!status.ready} onClick={()=>{if(status.playing)session!.pause();else void session!.play().catch(()=>{});}}>{status.playing?'영상 일시정지':'영상 재생'}</button><button className="button secondary" disabled={!session||!status.ready} onClick={()=>{session!.pause();session!.seek(0);}}>영상 처음으로</button></div><output aria-label="영상 재생 위치">{time(status.timeSeconds)} / {time(media.durationSeconds)}</output><label>재생 위치<input type="range" aria-label="영상 재생 위치 조절" min={0} max={media.durationSeconds} step={.1} value={status.timeSeconds} disabled={!session||!status.ready} onChange={e=>session!.seek(Number(e.target.value))}/></label><p className="field-hint">원본 {media.widthPx}×{media.heightPx}px · 재생 위치와 소리는 저장되지 않습니다.</p><label><input type="checkbox" checked={media.loop} disabled={artwork.locked} onChange={e=>patch({...media,loop:e.target.checked})}/>영상 반복 재생</label><label className="select-field"><span>화면 채우기</span><select aria-label="영상 화면 채우기" value={media.fit} disabled={artwork.locked} onChange={e=>patch({...media,fit:e.target.value as 'contain'|'cover'})}><option value="contain">전체 영상 · 여백 유지</option><option value="cover">스크린 채우기 · 가장자리 잘림</option></select></label><button className="button secondary" disabled={artwork.locked} onClick={()=>useEditor.getState().patchArtwork(artwork.id,{heightMm:artwork.widthMm*media.heightPx/media.widthPx})}>스크린을 원본 비율로</button><p className="field-hint">기본 음소거입니다. 미리보기의 소리 버튼으로 켤 수 있습니다. 동시에 네 영상까지 재생하며 새 영상을 재생하면 가장 먼저 재생한 영상을 멈춥니다.</p>{(error||status.error)&&<p role="alert" className="warning">{error||status.error}</p>}{session&&!status.ready&&!status.error&&<p role="status">영상을 읽는 중…</p>}</section>;
}
