import {useEffect,useRef,useState} from 'react';
import type {WallCandidate} from '../domain/wallCandidates';
import {detectPlanWalls} from '../lib/detectPlanWalls';
import {useEditor} from '../state/editor';
import {addReviewedWalls} from '../domain/reviewedWalls';
import {calibratePlan} from '../domain/plan';
export function WallCandidateDialog({onClose}:{onClose:()=>void}){
 const {project,commit,patchProject,notify}=useEditor();const reference=project.planReference;const imageUrl=project.planImageUrl;
 const dialog=useRef<HTMLDialogElement>(null),abort=useRef<AbortController|null>(null),revision=useRef(0);
 const initial=useRef({id:project.id,image:imageUrl});
 const [candidates,setCandidates]=useState<WallCandidate[]>([]),[chosen,setChosen]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [threshold,setThreshold]=useState(150),[minRatio,setMinRatio]=useState(0.05),[height,setHeight]=useState('3000'),[thickness,setThickness]=useState('150'),[knownLength,setKnownLength]=useState('');
 const [hasRun,setHasRun]=useState(false);
 async function analyze(){if(!imageUrl)return;abort.current?.abort();const control=new AbortController();abort.current=control;const run=++revision.current;setBusy(true);setError('');setChosen([]);setCandidates([]);try{const result=await detectPlanWalls(imageUrl,threshold,minRatio,control.signal);if(run===revision.current&&!control.signal.aborted){setCandidates(result);setHasRun(true);}}catch(e){if(!control.signal.aborted)setError((e as Error).message);}finally{if(run===revision.current)setBusy(false);}}
 useEffect(()=>{dialog.current?.showModal();void analyze();return()=>{revision.current++;abort.current?.abort();};},[]);
 useEffect(()=>{if(initial.current.image!==imageUrl||initial.current.id!==project.id)onClose();},[imageUrl,project.id,onClose]);
 if(!reference||!imageUrl)return null;
 function toggle(id:string){setChosen(ids=>ids.includes(id)?ids.filter(x=>x!==id):[...ids,id]);}
 const selected=candidates.filter(c=>chosen.includes(c.id));
 function calibrate(){try{if(!reference||selected.length!==1)return;const c=selected[0];patchProject({planReference:calibratePlan(reference,{x:c.start.x,z:c.start.y},{x:c.end.x,z:c.end.y},Number(knownLength))});setError('');}catch(e){setError((e as Error).message);}}
 function add(){try{const latest=useEditor.getState().project;if(latest.planImageUrl!==imageUrl||latest.id!==project.id)throw new Error('도면이 변경되었습니다. 다시 분석하세요.');const next=addReviewedWalls(latest,selected,Number(height),Number(thickness));const added=next.walls.length-latest.walls.length;commit(next);useEditor.getState().select({type:'wall',id:next.walls[latest.walls.length].id});notify(`${added}개의 벽을 추가했습니다. 끝점·높이·두께를 확인하세요.`);onClose();}catch(e){setError((e as Error).message);}}
 return <dialog ref={dialog} className="export-dialog wall-candidates-dialog" onCancel={onClose} aria-label="벽 후보 검토"><h2>벽 후보 검토 <small>실험 기능</small></h2><p>수평·수직의 긴 선을 찾습니다. 치수선·표제란도 포함될 수 있으며, 이중 벽선은 두 후보로 나올 수 있습니다. 맞는 선만 선택하세요.</p>
 <div className="candidate-settings"><label>선 대비<select aria-label="후보 선 대비" value={threshold} disabled={busy} onChange={e=>setThreshold(Number(e.target.value))}><option value={80}>진한 선만</option><option value={150}>보통</option><option value={210}>흐린 선 포함</option></select></label><label>최소 선 길이<select aria-label="후보 최소 길이" value={minRatio} disabled={busy} onChange={e=>setMinRatio(Number(e.target.value))}><option value={0.03}>짧게</option><option value={0.05}>보통</option><option value={0.1}>길게</option></select></label><button className="button secondary" disabled={busy} onClick={()=>void analyze()}>다시 분석</button></div>
 {busy&&<p role="status">도면의 선 후보를 찾는 중…</p>}{error&&<p role="alert" className="plan-quality-warning">{error}</p>}
 <svg className="candidate-preview" viewBox={`0 0 ${reference.widthPx} ${reference.heightPx}`} aria-label="도면 벽 후보 미리보기"><image href={imageUrl} width={reference.widthPx} height={reference.heightPx}/>{candidates.map((c,i)=><g key={c.id} onClick={()=>toggle(c.id)}><line x1={c.start.x} y1={c.start.y} x2={c.end.x} y2={c.end.y} stroke={chosen.includes(c.id)?'#365cf5':'#ed792c'} strokeWidth={Math.max(reference.widthPx/250,3)} strokeOpacity={0.85}/><line x1={c.start.x} y1={c.start.y} x2={c.end.x} y2={c.end.y} stroke="transparent" strokeWidth={reference.widthPx/45} style={{cursor:'pointer'}}/><text x={(c.start.x+c.end.x)/2} y={(c.start.y+c.end.y)/2} fill="#122965" stroke="white" strokeWidth={2} paintOrder="stroke" fontSize={reference.widthPx/55} pointerEvents="none">{i+1}</text></g>)}</svg>
 {hasRun&&!busy&&<p role="status">{candidates.length}개 후보 · {selected.length}개 선택{candidates.length===100?' · 표시 상한 100개, 영역을 좁혀 다시 분석하세요.':''}</p>}{hasRun&&!busy&&!candidates.length&&<p>후보를 찾지 못했습니다. 방향·대비·영역을 조정하거나 평면도에서 벽을 직접 추가하세요.</p>}
 <div className="candidate-list">{candidates.map((c,i)=><label key={c.id}><input type="checkbox" checked={chosen.includes(c.id)} onChange={()=>toggle(c.id)} aria-label={`벽 후보 ${i+1}`}/><span>{i+1}. {Math.abs(c.end.x-c.start.x)>Math.abs(c.end.y-c.start.y)?'수평':'수직'} · {Math.round(Math.hypot(c.end.x-c.start.x,c.end.y-c.start.y)*(reference.calibrated?reference.mmPerPixel:1)).toLocaleString()} {reference.calibrated?'mm':'px'}</span></label>)}</div>
 <div className="candidate-calibration"><strong>{reference.calibrated?'도면 축척 설정됨':'축척 보정 필요'}</strong><p>길이를 알고 있는 후보 하나를 선택하고 실제 길이를 입력하면 도면 축척을 설정합니다. 숫자나 눈금선과 혼동하지 않도록 확인하세요.</p><label>선택 선 실제 길이 (mm)<input aria-label="선택 선 실제 길이" type="number" min="1" value={knownLength} onChange={e=>setKnownLength(e.target.value)}/></label><button className="button secondary" disabled={busy||selected.length!==1||!knownLength} onClick={calibrate}>선택 선으로 축척 설정</button></div>
 <div className="candidate-settings"><label>벽 높이 (mm)<input aria-label="후보 벽 높이" type="number" min="1" max="20000" value={height} onChange={e=>setHeight(e.target.value)}/></label><label>벽 두께 (mm)<input aria-label="후보 벽 두께" type="number" min="1" max="2000" value={thickness} onChange={e=>setThickness(e.target.value)}/></label></div><p>높이·두께는 입력값입니다. 내부벽으로 추가되며, 추가 후 속성에서 끝점과 바닥 경계 용도를 조정할 수 있습니다. 기존 벽과 작품은 유지됩니다.</p>
 <div className="dialog-actions"><button className="button secondary" onClick={onClose}>닫기</button><button className="button primary" disabled={busy||!selected.length||!reference.calibrated} onClick={add}>선택한 {selected.length}개 벽 추가</button></div></dialog>;
}
