import { Component, Suspense, lazy, useCallback, useRef, useState } from 'react';
import type { ReactNode } from 'react';
import { MousePointer2, Ruler, Scan, PanelTop, Box, RotateCcw, Plus, Trash2 } from 'lucide-react';
import { useEditor } from '../state/editor';
import { IconButton } from './Controls';
import { PlanView } from './PlanView';
import { ElevationView } from './ElevationView';
const Gallery3D = lazy(() => import('./Gallery3D').then(m => ({ default: m.Gallery3D })));
class RenderBoundary extends Component<{ children: ReactNode }, { error: boolean }> {
  state = { error: false };
  static getDerivedStateFromError() { return { error: true }; }
  render() { return this.state.error ? <div className="render-error"><h2>3D 화면을 열지 못했습니다</h2><p>그래픽 가속 또는 작품 이미지를 확인해주세요.<br />평면도와 벽면도에서 작업을 계속할 수 있습니다.</p><button className="button secondary" onClick={() => useEditor.getState().setView('plan')}>평면도로 이동</button></div> : this.props.children; }
}
export function Workspace({ captureRef }: { captureRef: React.MutableRefObject<(() => void) | null> }) {
  const { project, view, setView, showDimensions, toggleDimensions, selected, setActiveWall, saveScene, restoreScene, deleteScene } = useEditor();
  const [reset, setReset] = useState(0), [cutaway, setCutaway] = useState(true), [sceneOpen, setSceneOpen] = useState(false);
  const sceneName = useRef<HTMLInputElement>(null);
  const captureReady = useCallback((capture: () => void) => { captureRef.current = capture; }, [captureRef]);
  return <main className="workspace"><div className="viewport-label">{view === '3d' ? '공간 미리보기' : view === 'plan' ? '평면도' : '벽면도'}<span>{view === '3d' ? '모서리를 열어 공간을 살펴보세요' : '실제 치수로 배치를 조정하세요'}</span></div><div className="viewport-toolbar"><span className="icon-button active" title="선택 도구 활성화" aria-label="선택 도구 활성화"><MousePointer2 size={18} /></span><span className="toolbar-divider" /><IconButton label="벽 추가" onClick={() => { useEditor.getState().addWall(); setView('plan'); }}><PanelTop size={18} /></IconButton><IconButton label="치수 표시" active={showDimensions} onClick={toggleDimensions}><Ruler size={18} /></IconButton><span className="toolbar-divider" /><IconButton label="기본 시점으로" onClick={() => setReset(n => n + 1)} disabled={view !== '3d'}><Scan size={18} /></IconButton></div>{view === '3d' && <label className="cutaway-toggle"><input type="checkbox" checked={cutaway} onChange={e => setCutaway(e.target.checked)} />벽 자동 숨김</label>}<div className="viewport-stage">{view === '3d' ? <RenderBoundary><Suspense fallback={<div className="loading-canvas"><Box size={30} strokeWidth={1.2} /><span>공간을 불러오는 중</span></div>}><Gallery3D reset={reset} onCaptureReady={captureReady} cutaway={cutaway} /></Suspense></RenderBoundary> : view === 'plan' ? <PlanView /> : <ElevationView />}</div><div className="view-navigation"><button className={view === '3d' ? 'active' : ''} onClick={() => setView('3d')}>3D</button><button className={view === 'plan' ? 'active' : ''} onClick={() => setView('plan')}>평면도</button><button className={view === 'elevation' ? 'active' : ''} onClick={() => { const art = project.artworks.find(a => a.id === selected[0]?.id); if (art) setActiveWall(art.wallId); setView('elevation'); }}>벽면도</button></div><button className={`scene-toggle ${sceneOpen ? 'active' : ''}`} onClick={() => setSceneOpen(!sceneOpen)}><RotateCcw size={14} />Scene {project.scenes.length > 0 && <span>{project.scenes.length}</span>}</button>{sceneOpen && <div className="scene-popover"><strong>배치안 저장</strong><p>작품 배치와 벽 표시 상태를 비교하세요.</p><div className="scene-create"><input aria-label="Scene 이름" ref={sceneName} placeholder={`Scene ${String.fromCharCode(65 + project.scenes.length)}`} maxLength={60} /><button className="icon-button active" aria-label="현재 Scene 저장" onClick={() => { saveScene(sceneName.current?.value.trim() || `Scene ${String.fromCharCode(65 + project.scenes.length)}`); if (sceneName.current) sceneName.current.value = ''; }}><Plus size={17} /></button></div>{project.scenes.map(s => <div className="scene-row" key={s.id}><button onClick={() => restoreScene(s.id)}>{s.name}<span>{s.artworks.length}개 작품</span></button><IconButton label={`${s.name} 삭제`} onClick={() => deleteScene(s.id)}><Trash2 size={14} /></IconButton></div>)}</div>}</main>;
}
