import {ScreenRecoveryBoundary} from './components/ScreenRecoveryBoundary';
import {lazy,Suspense} from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
const App=lazy(()=>import('./App'));
const ProjectInvitationPage=lazy(()=>import('./components/ProjectInvitationPage'));
const joinRoute=location.pathname.startsWith('/join/');
const joinMatch=location.pathname.match(/^\/join\/([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})\/?$/i);
const SharedViewer=lazy(()=>import('./components/SharedViewer'));
const Benchmark=import.meta.env.DEV?lazy(()=>import('./dev/RenderBenchmark')):null;
const benchmarkRoute=import.meta.env.DEV&&location.pathname==='/__render-benchmark';
const sharedRoute=location.pathname.startsWith('/s/');
const match=location.pathname.match(/^\/s\/([0-9a-f]{48})\/?$/);
createRoot(document.getElementById('root')!).render(<ScreenRecoveryBoundary name="시작 화면"><Suspense fallback={<div className="loading-canvas">화면을 불러오는 중…</div>}>{benchmarkRoute&&Benchmark?<Benchmark/>:joinRoute?<ProjectInvitationPage invitationId={joinMatch?.[1]??null}/>:sharedRoute?<SharedViewer shareId={match?.[1]??null}/>:<App/>}</Suspense></ScreenRecoveryBoundary>);
